// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocationCinemaReq struct {
	LocationId           int64    `protobuf:"varint,1,opt,name=locationId,proto3" json:"locationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationCinemaReq) Reset()         { *m = LocationCinemaReq{} }
func (m *LocationCinemaReq) String() string { return proto.CompactTextString(m) }
func (*LocationCinemaReq) ProtoMessage()    {}
func (*LocationCinemaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{0}
}

func (m *LocationCinemaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationCinemaReq.Unmarshal(m, b)
}
func (m *LocationCinemaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationCinemaReq.Marshal(b, m, deterministic)
}
func (m *LocationCinemaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationCinemaReq.Merge(m, src)
}
func (m *LocationCinemaReq) XXX_Size() int {
	return xxx_messageInfo_LocationCinemaReq.Size(m)
}
func (m *LocationCinemaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationCinemaReq.DiscardUnknown(m)
}

var xxx_messageInfo_LocationCinemaReq proto.InternalMessageInfo

func (m *LocationCinemaReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

type LocationCinemaRsp struct {
	Cinemas              []*Cinema `protobuf:"bytes,1,rep,name=cinemas,proto3" json:"cinemas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocationCinemaRsp) Reset()         { *m = LocationCinemaRsp{} }
func (m *LocationCinemaRsp) String() string { return proto.CompactTextString(m) }
func (*LocationCinemaRsp) ProtoMessage()    {}
func (*LocationCinemaRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{1}
}

func (m *LocationCinemaRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationCinemaRsp.Unmarshal(m, b)
}
func (m *LocationCinemaRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationCinemaRsp.Marshal(b, m, deterministic)
}
func (m *LocationCinemaRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationCinemaRsp.Merge(m, src)
}
func (m *LocationCinemaRsp) XXX_Size() int {
	return xxx_messageInfo_LocationCinemaRsp.Size(m)
}
func (m *LocationCinemaRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationCinemaRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LocationCinemaRsp proto.InternalMessageInfo

func (m *LocationCinemaRsp) GetCinemas() []*Cinema {
	if m != nil {
		return m.Cinemas
	}
	return nil
}

type Cinema struct {
	CinemaName           string   `protobuf:"bytes,1,opt,name=cinemaName,proto3" json:"cinemaName,omitempty"`
	CinemaAddress        string   `protobuf:"bytes,2,opt,name=cinemaAddress,proto3" json:"cinemaAddress,omitempty"`
	CinemaSupport        string   `protobuf:"bytes,3,opt,name=cinemaSupport,proto3" json:"cinemaSupport,omitempty"`
	CinemaCard           int64    `protobuf:"varint,4,opt,name=cinemaCard,proto3" json:"cinemaCard,omitempty"`
	CinemaMinPrice       int64    `protobuf:"varint,5,opt,name=cinemaMinPrice,proto3" json:"cinemaMinPrice,omitempty"`
	CinemaDiscount       int64    `protobuf:"varint,6,opt,name=cinemaDiscount,proto3" json:"cinemaDiscount,omitempty"`
	CinemaId             int64    `protobuf:"varint,7,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cinema) Reset()         { *m = Cinema{} }
func (m *Cinema) String() string { return proto.CompactTextString(m) }
func (*Cinema) ProtoMessage()    {}
func (*Cinema) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{2}
}

func (m *Cinema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cinema.Unmarshal(m, b)
}
func (m *Cinema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cinema.Marshal(b, m, deterministic)
}
func (m *Cinema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cinema.Merge(m, src)
}
func (m *Cinema) XXX_Size() int {
	return xxx_messageInfo_Cinema.Size(m)
}
func (m *Cinema) XXX_DiscardUnknown() {
	xxx_messageInfo_Cinema.DiscardUnknown(m)
}

var xxx_messageInfo_Cinema proto.InternalMessageInfo

func (m *Cinema) GetCinemaName() string {
	if m != nil {
		return m.CinemaName
	}
	return ""
}

func (m *Cinema) GetCinemaAddress() string {
	if m != nil {
		return m.CinemaAddress
	}
	return ""
}

func (m *Cinema) GetCinemaSupport() string {
	if m != nil {
		return m.CinemaSupport
	}
	return ""
}

func (m *Cinema) GetCinemaCard() int64 {
	if m != nil {
		return m.CinemaCard
	}
	return 0
}

func (m *Cinema) GetCinemaMinPrice() int64 {
	if m != nil {
		return m.CinemaMinPrice
	}
	return 0
}

func (m *Cinema) GetCinemaDiscount() int64 {
	if m != nil {
		return m.CinemaDiscount
	}
	return 0
}

func (m *Cinema) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type GetCinemaMessageReq struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	LocationId           int64    `protobuf:"varint,2,opt,name=locationId,proto3" json:"locationId,omitempty"`
	Day                  string   `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCinemaMessageReq) Reset()         { *m = GetCinemaMessageReq{} }
func (m *GetCinemaMessageReq) String() string { return proto.CompactTextString(m) }
func (*GetCinemaMessageReq) ProtoMessage()    {}
func (*GetCinemaMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{3}
}

func (m *GetCinemaMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaMessageReq.Unmarshal(m, b)
}
func (m *GetCinemaMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaMessageReq.Marshal(b, m, deterministic)
}
func (m *GetCinemaMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaMessageReq.Merge(m, src)
}
func (m *GetCinemaMessageReq) XXX_Size() int {
	return xxx_messageInfo_GetCinemaMessageReq.Size(m)
}
func (m *GetCinemaMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaMessageReq proto.InternalMessageInfo

func (m *GetCinemaMessageReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *GetCinemaMessageReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *GetCinemaMessageReq) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

type GetCinemaMessageRsp struct {
	CinemaName           string   `protobuf:"bytes,1,opt,name=cinemaName,proto3" json:"cinemaName,omitempty"`
	CinemaAddress        string   `protobuf:"bytes,2,opt,name=cinemaAddress,proto3" json:"cinemaAddress,omitempty"`
	CinemaSupport        string   `protobuf:"bytes,3,opt,name=cinemaSupport,proto3" json:"cinemaSupport,omitempty"`
	CinemaCard           int64    `protobuf:"varint,4,opt,name=cinemaCard,proto3" json:"cinemaCard,omitempty"`
	CinemaMinPrice       int64    `protobuf:"varint,5,opt,name=cinemaMinPrice,proto3" json:"cinemaMinPrice,omitempty"`
	CinemaDiscount       int64    `protobuf:"varint,6,opt,name=cinemaDiscount,proto3" json:"cinemaDiscount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCinemaMessageRsp) Reset()         { *m = GetCinemaMessageRsp{} }
func (m *GetCinemaMessageRsp) String() string { return proto.CompactTextString(m) }
func (*GetCinemaMessageRsp) ProtoMessage()    {}
func (*GetCinemaMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{4}
}

func (m *GetCinemaMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaMessageRsp.Unmarshal(m, b)
}
func (m *GetCinemaMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaMessageRsp.Marshal(b, m, deterministic)
}
func (m *GetCinemaMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaMessageRsp.Merge(m, src)
}
func (m *GetCinemaMessageRsp) XXX_Size() int {
	return xxx_messageInfo_GetCinemaMessageRsp.Size(m)
}
func (m *GetCinemaMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaMessageRsp proto.InternalMessageInfo

func (m *GetCinemaMessageRsp) GetCinemaName() string {
	if m != nil {
		return m.CinemaName
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaAddress() string {
	if m != nil {
		return m.CinemaAddress
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaSupport() string {
	if m != nil {
		return m.CinemaSupport
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaCard() int64 {
	if m != nil {
		return m.CinemaCard
	}
	return 0
}

func (m *GetCinemaMessageRsp) GetCinemaMinPrice() int64 {
	if m != nil {
		return m.CinemaMinPrice
	}
	return 0
}

func (m *GetCinemaMessageRsp) GetCinemaDiscount() int64 {
	if m != nil {
		return m.CinemaDiscount
	}
	return 0
}

type GetCinemaMessageByCidReq struct {
	CinemaId             int64    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCinemaMessageByCidReq) Reset()         { *m = GetCinemaMessageByCidReq{} }
func (m *GetCinemaMessageByCidReq) String() string { return proto.CompactTextString(m) }
func (*GetCinemaMessageByCidReq) ProtoMessage()    {}
func (*GetCinemaMessageByCidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{5}
}

func (m *GetCinemaMessageByCidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaMessageByCidReq.Unmarshal(m, b)
}
func (m *GetCinemaMessageByCidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaMessageByCidReq.Marshal(b, m, deterministic)
}
func (m *GetCinemaMessageByCidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaMessageByCidReq.Merge(m, src)
}
func (m *GetCinemaMessageByCidReq) XXX_Size() int {
	return xxx_messageInfo_GetCinemaMessageByCidReq.Size(m)
}
func (m *GetCinemaMessageByCidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaMessageByCidReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaMessageByCidReq proto.InternalMessageInfo

func (m *GetCinemaMessageByCidReq) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type FilmMessage struct {
	FilmName             string   `protobuf:"bytes,1,opt,name=filmName,proto3" json:"filmName,omitempty"`
	RatingFinal          float32  `protobuf:"fixed32,2,opt,name=ratingFinal,proto3" json:"ratingFinal,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ActorName            []string `protobuf:"bytes,5,rep,name=actorName,proto3" json:"actorName,omitempty"`
	MovieId              int64    `protobuf:"varint,6,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Img                  string   `protobuf:"bytes,7,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilmMessage) Reset()         { *m = FilmMessage{} }
func (m *FilmMessage) String() string { return proto.CompactTextString(m) }
func (*FilmMessage) ProtoMessage()    {}
func (*FilmMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{6}
}

func (m *FilmMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilmMessage.Unmarshal(m, b)
}
func (m *FilmMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilmMessage.Marshal(b, m, deterministic)
}
func (m *FilmMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilmMessage.Merge(m, src)
}
func (m *FilmMessage) XXX_Size() int {
	return xxx_messageInfo_FilmMessage.Size(m)
}
func (m *FilmMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FilmMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FilmMessage proto.InternalMessageInfo

func (m *FilmMessage) GetFilmName() string {
	if m != nil {
		return m.FilmName
	}
	return ""
}

func (m *FilmMessage) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

func (m *FilmMessage) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *FilmMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FilmMessage) GetActorName() []string {
	if m != nil {
		return m.ActorName
	}
	return nil
}

func (m *FilmMessage) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *FilmMessage) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type GetCinemaMessageByCidRsp struct {
	Cinema               *Cinema        `protobuf:"bytes,1,opt,name=cinema,proto3" json:"cinema,omitempty"`
	FilmMessage          []*FilmMessage `protobuf:"bytes,2,rep,name=filmMessage,proto3" json:"filmMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCinemaMessageByCidRsp) Reset()         { *m = GetCinemaMessageByCidRsp{} }
func (m *GetCinemaMessageByCidRsp) String() string { return proto.CompactTextString(m) }
func (*GetCinemaMessageByCidRsp) ProtoMessage()    {}
func (*GetCinemaMessageByCidRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{7}
}

func (m *GetCinemaMessageByCidRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCinemaMessageByCidRsp.Unmarshal(m, b)
}
func (m *GetCinemaMessageByCidRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCinemaMessageByCidRsp.Marshal(b, m, deterministic)
}
func (m *GetCinemaMessageByCidRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCinemaMessageByCidRsp.Merge(m, src)
}
func (m *GetCinemaMessageByCidRsp) XXX_Size() int {
	return xxx_messageInfo_GetCinemaMessageByCidRsp.Size(m)
}
func (m *GetCinemaMessageByCidRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCinemaMessageByCidRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCinemaMessageByCidRsp proto.InternalMessageInfo

func (m *GetCinemaMessageByCidRsp) GetCinema() *Cinema {
	if m != nil {
		return m.Cinema
	}
	return nil
}

func (m *GetCinemaMessageByCidRsp) GetFilmMessage() []*FilmMessage {
	if m != nil {
		return m.FilmMessage
	}
	return nil
}

type GetMovieHallByMHIdReq struct {
	MhId                 int64    `protobuf:"varint,1,opt,name=mhId,proto3" json:"mhId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieHallByMHIdReq) Reset()         { *m = GetMovieHallByMHIdReq{} }
func (m *GetMovieHallByMHIdReq) String() string { return proto.CompactTextString(m) }
func (*GetMovieHallByMHIdReq) ProtoMessage()    {}
func (*GetMovieHallByMHIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{8}
}

func (m *GetMovieHallByMHIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieHallByMHIdReq.Unmarshal(m, b)
}
func (m *GetMovieHallByMHIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieHallByMHIdReq.Marshal(b, m, deterministic)
}
func (m *GetMovieHallByMHIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieHallByMHIdReq.Merge(m, src)
}
func (m *GetMovieHallByMHIdReq) XXX_Size() int {
	return xxx_messageInfo_GetMovieHallByMHIdReq.Size(m)
}
func (m *GetMovieHallByMHIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieHallByMHIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieHallByMHIdReq proto.InternalMessageInfo

func (m *GetMovieHallByMHIdReq) GetMhId() int64 {
	if m != nil {
		return m.MhId
	}
	return 0
}

type GetMovieHallByMHIdRsp struct {
	MhAddress            string   `protobuf:"bytes,1,opt,name=mhAddress,proto3" json:"mhAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieHallByMHIdRsp) Reset()         { *m = GetMovieHallByMHIdRsp{} }
func (m *GetMovieHallByMHIdRsp) String() string { return proto.CompactTextString(m) }
func (*GetMovieHallByMHIdRsp) ProtoMessage()    {}
func (*GetMovieHallByMHIdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_780650c131bcaf97, []int{9}
}

func (m *GetMovieHallByMHIdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieHallByMHIdRsp.Unmarshal(m, b)
}
func (m *GetMovieHallByMHIdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieHallByMHIdRsp.Marshal(b, m, deterministic)
}
func (m *GetMovieHallByMHIdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieHallByMHIdRsp.Merge(m, src)
}
func (m *GetMovieHallByMHIdRsp) XXX_Size() int {
	return xxx_messageInfo_GetMovieHallByMHIdRsp.Size(m)
}
func (m *GetMovieHallByMHIdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieHallByMHIdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieHallByMHIdRsp proto.InternalMessageInfo

func (m *GetMovieHallByMHIdRsp) GetMhAddress() string {
	if m != nil {
		return m.MhAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*LocationCinemaReq)(nil), "pb.LocationCinemaReq")
	proto.RegisterType((*LocationCinemaRsp)(nil), "pb.LocationCinemaRsp")
	proto.RegisterType((*Cinema)(nil), "pb.Cinema")
	proto.RegisterType((*GetCinemaMessageReq)(nil), "pb.GetCinemaMessageReq")
	proto.RegisterType((*GetCinemaMessageRsp)(nil), "pb.GetCinemaMessageRsp")
	proto.RegisterType((*GetCinemaMessageByCidReq)(nil), "pb.GetCinemaMessageByCidReq")
	proto.RegisterType((*FilmMessage)(nil), "pb.FilmMessage")
	proto.RegisterType((*GetCinemaMessageByCidRsp)(nil), "pb.GetCinemaMessageByCidRsp")
	proto.RegisterType((*GetMovieHallByMHIdReq)(nil), "pb.GetMovieHallByMHIdReq")
	proto.RegisterType((*GetMovieHallByMHIdRsp)(nil), "pb.GetMovieHallByMHIdRsp")
}

func init() { proto.RegisterFile("cinema.ext.proto", fileDescriptor_780650c131bcaf97) }

var fileDescriptor_780650c131bcaf97 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0xc7, 0x7f, 0xb6, 0x5b, 0xf7, 0x97, 0x13, 0xd6, 0x65, 0x67, 0x74, 0x68, 0xa1, 0x8c, 0x20,
	0xca, 0x08, 0x0c, 0x02, 0x6b, 0xd9, 0x60, 0x77, 0x5b, 0xb3, 0xb5, 0x0d, 0x34, 0x63, 0xb8, 0xec,
	0x01, 0x14, 0x5b, 0x4d, 0x04, 0xfe, 0xa3, 0x5a, 0x6a, 0x69, 0xee, 0xf6, 0x6a, 0x7b, 0xa4, 0x5d,
	0xee, 0x6e, 0x48, 0x72, 0x62, 0xe7, 0xdf, 0x1e, 0x60, 0x77, 0x3a, 0xdf, 0xf3, 0x95, 0x8f, 0xce,
	0x47, 0xc7, 0x82, 0x4e, 0x2c, 0x72, 0x9e, 0xb1, 0x01, 0x7f, 0xd4, 0x03, 0x59, 0x16, 0xba, 0x40,
	0x5f, 0x4e, 0xe8, 0x19, 0x3c, 0xbb, 0x2e, 0x62, 0xa6, 0x45, 0x91, 0x0f, 0x6d, 0x3e, 0xe2, 0x77,
	0xf8, 0x0a, 0x20, 0xad, 0xc4, 0x51, 0x42, 0xbc, 0x9e, 0xd7, 0x0f, 0xa2, 0x86, 0x42, 0x3f, 0x6c,
	0x6c, 0x52, 0x12, 0x4f, 0xe0, 0xc0, 0x55, 0x50, 0xc4, 0xeb, 0x05, 0xfd, 0xf6, 0x29, 0x0c, 0xe4,
	0x64, 0x50, 0xe5, 0x17, 0x29, 0xfa, 0xc3, 0x87, 0xd0, 0x69, 0xa6, 0x8a, 0x53, 0xbf, 0xb2, 0x8c,
	0xdb, 0x2a, 0xad, 0xa8, 0xa1, 0xe0, 0x09, 0x3c, 0x71, 0xd1, 0xa7, 0x24, 0x29, 0xb9, 0x52, 0xc4,
	0xb7, 0x96, 0x55, 0xb1, 0x76, 0xdd, 0xdc, 0x4b, 0x59, 0x94, 0x9a, 0x04, 0x4d, 0x57, 0x25, 0xd6,
	0xb5, 0x86, 0xac, 0x4c, 0xc8, 0x9e, 0xeb, 0xa8, 0x56, 0xf0, 0x35, 0x1c, 0xba, 0x68, 0x2c, 0xf2,
	0x6f, 0xa5, 0x88, 0x39, 0xd9, 0xb7, 0x9e, 0x35, 0xb5, 0xf6, 0x7d, 0x16, 0x2a, 0x2e, 0xee, 0x73,
	0x4d, 0xc2, 0xa6, 0x6f, 0xa1, 0x62, 0x17, 0xfe, 0x77, 0xca, 0x28, 0x21, 0x07, 0xd6, 0xb1, 0x8c,
	0x29, 0x83, 0xe7, 0x97, 0x5c, 0x3b, 0x08, 0x63, 0xae, 0x14, 0x9b, 0x72, 0x03, 0x9d, 0xc0, 0x41,
	0x56, 0x3c, 0x08, 0xbe, 0x24, 0xbe, 0x08, 0xd7, 0xae, 0xc3, 0x5f, 0xbf, 0x0e, 0xec, 0x40, 0x90,
	0xb0, 0x79, 0xd5, 0xb8, 0x59, 0xd2, 0x5f, 0xde, 0x96, 0x1a, 0x4a, 0xfe, 0xcb, 0xc8, 0xe9, 0x7b,
	0x20, 0xeb, 0x2d, 0x9f, 0xcf, 0x87, 0x22, 0x31, 0x6c, 0x9b, 0xd7, 0xe1, 0xad, 0x5d, 0xc7, 0x4f,
	0x0f, 0xda, 0x17, 0x22, 0xcd, 0xaa, 0x3d, 0xc6, 0x7b, 0x2b, 0xd2, 0xac, 0x41, 0x68, 0x19, 0x63,
	0x0f, 0xda, 0x25, 0xd3, 0x22, 0x9f, 0x5e, 0x88, 0x9c, 0xa5, 0x96, 0x8e, 0x1f, 0x35, 0x25, 0x7c,
	0x01, 0x61, 0xca, 0xf3, 0xa9, 0x9e, 0x59, 0x28, 0x41, 0x54, 0x45, 0x88, 0xb0, 0xa7, 0xe7, 0x92,
	0x5b, 0x0e, 0xad, 0xc8, 0xae, 0xf1, 0x18, 0x5a, 0x2c, 0xd6, 0x45, 0x69, 0x4b, 0xed, 0xf7, 0x82,
	0x7e, 0x2b, 0xaa, 0x85, 0xe6, 0x3c, 0x84, 0xab, 0xf3, 0xd0, 0x81, 0x40, 0x64, 0x53, 0x3b, 0x57,
	0xad, 0xc8, 0x2c, 0xe9, 0xdd, 0xae, 0xde, 0x95, 0x44, 0x0a, 0xa1, 0xeb, 0xd5, 0x76, 0xb3, 0xfa,
	0x5b, 0x56, 0x19, 0x7c, 0x0b, 0xed, 0xdb, 0x1a, 0x01, 0xf1, 0xed, 0xff, 0xfb, 0xd4, 0x18, 0x1b,
	0x64, 0xa2, 0xa6, 0x87, 0xbe, 0x81, 0xa3, 0x4b, 0xae, 0xc7, 0xe6, 0x48, 0x57, 0x2c, 0x4d, 0xcf,
	0xe7, 0xe3, 0xab, 0x91, 0x65, 0x8d, 0xb0, 0x97, 0xcd, 0x96, 0x9c, 0xed, 0x9a, 0xbe, 0xdb, 0x6a,
	0x56, 0xd2, 0x20, 0xc8, 0x66, 0x8b, 0x61, 0x73, 0xb4, 0x6b, 0xe1, 0xf4, 0xb7, 0x07, 0x1d, 0x77,
	0xd2, 0x1b, 0x5e, 0x3e, 0x88, 0x98, 0x7f, 0x79, 0xd4, 0xf8, 0x11, 0x0e, 0x57, 0x1f, 0x1f, 0x3c,
	0x32, 0x07, 0xdd, 0x78, 0xc5, 0xba, 0xdb, 0x64, 0x25, 0xe9, 0x7f, 0xf8, 0xdd, 0x9e, 0x66, 0x93,
	0x16, 0x1e, 0x9b, 0x1d, 0xbb, 0x86, 0xa8, 0xfb, 0x97, 0xac, 0xfd, 0xec, 0x35, 0xe0, 0x66, 0x93,
	0xf8, 0xb2, 0xda, 0xb5, 0x49, 0xaa, 0xbb, 0x2b, 0x65, 0xbe, 0x36, 0x09, 0xed, 0x1b, 0x7d, 0xf6,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x78, 0xca, 0x53, 0xb7, 0x05, 0x00, 0x00,
}
