// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotCommentReq struct {
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotCommentReq) Reset()         { *m = HotCommentReq{} }
func (m *HotCommentReq) String() string { return proto.CompactTextString(m) }
func (*HotCommentReq) ProtoMessage()    {}
func (*HotCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{0}
}

func (m *HotCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotCommentReq.Unmarshal(m, b)
}
func (m *HotCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotCommentReq.Marshal(b, m, deterministic)
}
func (m *HotCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotCommentReq.Merge(m, src)
}
func (m *HotCommentReq) XXX_Size() int {
	return xxx_messageInfo_HotCommentReq.Size(m)
}
func (m *HotCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HotCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_HotCommentReq proto.InternalMessageInfo

func (m *HotCommentReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type HotCommentRsp struct {
	Data                 *CommentData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HotCommentRsp) Reset()         { *m = HotCommentRsp{} }
func (m *HotCommentRsp) String() string { return proto.CompactTextString(m) }
func (*HotCommentRsp) ProtoMessage()    {}
func (*HotCommentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{1}
}

func (m *HotCommentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotCommentRsp.Unmarshal(m, b)
}
func (m *HotCommentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotCommentRsp.Marshal(b, m, deterministic)
}
func (m *HotCommentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotCommentRsp.Merge(m, src)
}
func (m *HotCommentRsp) XXX_Size() int {
	return xxx_messageInfo_HotCommentRsp.Size(m)
}
func (m *HotCommentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HotCommentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HotCommentRsp proto.InternalMessageInfo

func (m *HotCommentRsp) GetData() *CommentData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommentData struct {
	Mini                 *CommentMini `protobuf:"bytes,1,opt,name=mini,proto3" json:"mini,omitempty"`
	Plus                 *CommentPlus `protobuf:"bytes,2,opt,name=plus,proto3" json:"plus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommentData) Reset()         { *m = CommentData{} }
func (m *CommentData) String() string { return proto.CompactTextString(m) }
func (*CommentData) ProtoMessage()    {}
func (*CommentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{2}
}

func (m *CommentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentData.Unmarshal(m, b)
}
func (m *CommentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentData.Marshal(b, m, deterministic)
}
func (m *CommentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentData.Merge(m, src)
}
func (m *CommentData) XXX_Size() int {
	return xxx_messageInfo_CommentData.Size(m)
}
func (m *CommentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentData.DiscardUnknown(m)
}

var xxx_messageInfo_CommentData proto.InternalMessageInfo

func (m *CommentData) GetMini() *CommentMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

func (m *CommentData) GetPlus() *CommentPlus {
	if m != nil {
		return m.Plus
	}
	return nil
}

type CommentMini struct {
	List                 []*CommentRecord `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CommentMini) Reset()         { *m = CommentMini{} }
func (m *CommentMini) String() string { return proto.CompactTextString(m) }
func (*CommentMini) ProtoMessage()    {}
func (*CommentMini) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{3}
}

func (m *CommentMini) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentMini.Unmarshal(m, b)
}
func (m *CommentMini) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentMini.Marshal(b, m, deterministic)
}
func (m *CommentMini) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentMini.Merge(m, src)
}
func (m *CommentMini) XXX_Size() int {
	return xxx_messageInfo_CommentMini.Size(m)
}
func (m *CommentMini) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentMini.DiscardUnknown(m)
}

var xxx_messageInfo_CommentMini proto.InternalMessageInfo

func (m *CommentMini) GetList() []*CommentRecord {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentMini) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CommentPlus struct {
	List                 []*CommentRecord `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CommentPlus) Reset()         { *m = CommentPlus{} }
func (m *CommentPlus) String() string { return proto.CompactTextString(m) }
func (*CommentPlus) ProtoMessage()    {}
func (*CommentPlus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{4}
}

func (m *CommentPlus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentPlus.Unmarshal(m, b)
}
func (m *CommentPlus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentPlus.Marshal(b, m, deterministic)
}
func (m *CommentPlus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentPlus.Merge(m, src)
}
func (m *CommentPlus) XXX_Size() int {
	return xxx_messageInfo_CommentPlus.Size(m)
}
func (m *CommentPlus) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentPlus.DiscardUnknown(m)
}

var xxx_messageInfo_CommentPlus proto.InternalMessageInfo

func (m *CommentPlus) GetList() []*CommentRecord {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentPlus) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CommentRecord struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreateAt             string   `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpNum                int64    `protobuf:"varint,6,opt,name=upNum,proto3" json:"upNum,omitempty"`
	CommentID            int64    `protobuf:"varint,7,opt,name=commentID,proto3" json:"commentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRecord) Reset()         { *m = CommentRecord{} }
func (m *CommentRecord) String() string { return proto.CompactTextString(m) }
func (*CommentRecord) ProtoMessage()    {}
func (*CommentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{5}
}

func (m *CommentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRecord.Unmarshal(m, b)
}
func (m *CommentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRecord.Marshal(b, m, deterministic)
}
func (m *CommentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRecord.Merge(m, src)
}
func (m *CommentRecord) XXX_Size() int {
	return xxx_messageInfo_CommentRecord.Size(m)
}
func (m *CommentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRecord proto.InternalMessageInfo

func (m *CommentRecord) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CommentRecord) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentRecord) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *CommentRecord) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CommentRecord) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *CommentRecord) GetUpNum() int64 {
	if m != nil {
		return m.UpNum
	}
	return 0
}

func (m *CommentRecord) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

type MakeCommentReq struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeCommentReq) Reset()         { *m = MakeCommentReq{} }
func (m *MakeCommentReq) String() string { return proto.CompactTextString(m) }
func (*MakeCommentReq) ProtoMessage()    {}
func (*MakeCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{6}
}

func (m *MakeCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeCommentReq.Unmarshal(m, b)
}
func (m *MakeCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeCommentReq.Marshal(b, m, deterministic)
}
func (m *MakeCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeCommentReq.Merge(m, src)
}
func (m *MakeCommentReq) XXX_Size() int {
	return xxx_messageInfo_MakeCommentReq.Size(m)
}
func (m *MakeCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeCommentReq proto.InternalMessageInfo

func (m *MakeCommentReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *MakeCommentReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MakeCommentReq) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *MakeCommentReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *MakeCommentReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MakeCommentReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MakeCommentRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeCommentRsp) Reset()         { *m = MakeCommentRsp{} }
func (m *MakeCommentRsp) String() string { return proto.CompactTextString(m) }
func (*MakeCommentRsp) ProtoMessage()    {}
func (*MakeCommentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{7}
}

func (m *MakeCommentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeCommentRsp.Unmarshal(m, b)
}
func (m *MakeCommentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeCommentRsp.Marshal(b, m, deterministic)
}
func (m *MakeCommentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeCommentRsp.Merge(m, src)
}
func (m *MakeCommentRsp) XXX_Size() int {
	return xxx_messageInfo_MakeCommentRsp.Size(m)
}
func (m *MakeCommentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeCommentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MakeCommentRsp proto.InternalMessageInfo

type UpNumCommentReq struct {
	CommentID            int64    `protobuf:"varint,1,opt,name=commentID,proto3" json:"commentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpNumCommentReq) Reset()         { *m = UpNumCommentReq{} }
func (m *UpNumCommentReq) String() string { return proto.CompactTextString(m) }
func (*UpNumCommentReq) ProtoMessage()    {}
func (*UpNumCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{8}
}

func (m *UpNumCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpNumCommentReq.Unmarshal(m, b)
}
func (m *UpNumCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpNumCommentReq.Marshal(b, m, deterministic)
}
func (m *UpNumCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpNumCommentReq.Merge(m, src)
}
func (m *UpNumCommentReq) XXX_Size() int {
	return xxx_messageInfo_UpNumCommentReq.Size(m)
}
func (m *UpNumCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpNumCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpNumCommentReq proto.InternalMessageInfo

func (m *UpNumCommentReq) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

type UpNumCommentRsp struct {
	UpNum                int64    `protobuf:"varint,1,opt,name=upNum,proto3" json:"upNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpNumCommentRsp) Reset()         { *m = UpNumCommentRsp{} }
func (m *UpNumCommentRsp) String() string { return proto.CompactTextString(m) }
func (*UpNumCommentRsp) ProtoMessage()    {}
func (*UpNumCommentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{9}
}

func (m *UpNumCommentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpNumCommentRsp.Unmarshal(m, b)
}
func (m *UpNumCommentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpNumCommentRsp.Marshal(b, m, deterministic)
}
func (m *UpNumCommentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpNumCommentRsp.Merge(m, src)
}
func (m *UpNumCommentRsp) XXX_Size() int {
	return xxx_messageInfo_UpNumCommentRsp.Size(m)
}
func (m *UpNumCommentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpNumCommentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpNumCommentRsp proto.InternalMessageInfo

func (m *UpNumCommentRsp) GetUpNum() int64 {
	if m != nil {
		return m.UpNum
	}
	return 0
}

type MyCommentsReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyCommentsReq) Reset()         { *m = MyCommentsReq{} }
func (m *MyCommentsReq) String() string { return proto.CompactTextString(m) }
func (*MyCommentsReq) ProtoMessage()    {}
func (*MyCommentsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{10}
}

func (m *MyCommentsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyCommentsReq.Unmarshal(m, b)
}
func (m *MyCommentsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyCommentsReq.Marshal(b, m, deterministic)
}
func (m *MyCommentsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyCommentsReq.Merge(m, src)
}
func (m *MyCommentsReq) XXX_Size() int {
	return xxx_messageInfo_MyCommentsReq.Size(m)
}
func (m *MyCommentsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MyCommentsReq.DiscardUnknown(m)
}

var xxx_messageInfo_MyCommentsReq proto.InternalMessageInfo

func (m *MyCommentsReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MyCommentsRsp struct {
	MyComments           []*MyComment `protobuf:"bytes,1,rep,name=myComments,proto3" json:"myComments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MyCommentsRsp) Reset()         { *m = MyCommentsRsp{} }
func (m *MyCommentsRsp) String() string { return proto.CompactTextString(m) }
func (*MyCommentsRsp) ProtoMessage()    {}
func (*MyCommentsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{11}
}

func (m *MyCommentsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyCommentsRsp.Unmarshal(m, b)
}
func (m *MyCommentsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyCommentsRsp.Marshal(b, m, deterministic)
}
func (m *MyCommentsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyCommentsRsp.Merge(m, src)
}
func (m *MyCommentsRsp) XXX_Size() int {
	return xxx_messageInfo_MyCommentsRsp.Size(m)
}
func (m *MyCommentsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MyCommentsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MyCommentsRsp proto.InternalMessageInfo

func (m *MyCommentsRsp) GetMyComments() []*MyComment {
	if m != nil {
		return m.MyComments
	}
	return nil
}

type MyComment struct {
	FilmImage            string   `protobuf:"bytes,1,opt,name=filmImage,proto3" json:"filmImage,omitempty"`
	FilmName             string   `protobuf:"bytes,2,opt,name=filmName,proto3" json:"filmName,omitempty"`
	Score                string   `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	CommentID            int64    `protobuf:"varint,4,opt,name=commentID,proto3" json:"commentID,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	UpNum                int64    `protobuf:"varint,6,opt,name=upNum,proto3" json:"upNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyComment) Reset()         { *m = MyComment{} }
func (m *MyComment) String() string { return proto.CompactTextString(m) }
func (*MyComment) ProtoMessage()    {}
func (*MyComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{12}
}

func (m *MyComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyComment.Unmarshal(m, b)
}
func (m *MyComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyComment.Marshal(b, m, deterministic)
}
func (m *MyComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyComment.Merge(m, src)
}
func (m *MyComment) XXX_Size() int {
	return xxx_messageInfo_MyComment.Size(m)
}
func (m *MyComment) XXX_DiscardUnknown() {
	xxx_messageInfo_MyComment.DiscardUnknown(m)
}

var xxx_messageInfo_MyComment proto.InternalMessageInfo

func (m *MyComment) GetFilmImage() string {
	if m != nil {
		return m.FilmImage
	}
	return ""
}

func (m *MyComment) GetFilmName() string {
	if m != nil {
		return m.FilmName
	}
	return ""
}

func (m *MyComment) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *MyComment) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

func (m *MyComment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MyComment) GetUpNum() int64 {
	if m != nil {
		return m.UpNum
	}
	return 0
}

type DeleteCommentReq struct {
	CommentID            int64    `protobuf:"varint,1,opt,name=commentID,proto3" json:"commentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentReq) Reset()         { *m = DeleteCommentReq{} }
func (m *DeleteCommentReq) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentReq) ProtoMessage()    {}
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{13}
}

func (m *DeleteCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentReq.Unmarshal(m, b)
}
func (m *DeleteCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentReq.Marshal(b, m, deterministic)
}
func (m *DeleteCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentReq.Merge(m, src)
}
func (m *DeleteCommentReq) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentReq.Size(m)
}
func (m *DeleteCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentReq proto.InternalMessageInfo

func (m *DeleteCommentReq) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

type DeleteCommentRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentRsp) Reset()         { *m = DeleteCommentRsp{} }
func (m *DeleteCommentRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentRsp) ProtoMessage()    {}
func (*DeleteCommentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f0800a31d81040, []int{14}
}

func (m *DeleteCommentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentRsp.Unmarshal(m, b)
}
func (m *DeleteCommentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentRsp.Marshal(b, m, deterministic)
}
func (m *DeleteCommentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentRsp.Merge(m, src)
}
func (m *DeleteCommentRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentRsp.Size(m)
}
func (m *DeleteCommentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HotCommentReq)(nil), "pb.HotCommentReq")
	proto.RegisterType((*HotCommentRsp)(nil), "pb.HotCommentRsp")
	proto.RegisterType((*CommentData)(nil), "pb.CommentData")
	proto.RegisterType((*CommentMini)(nil), "pb.CommentMini")
	proto.RegisterType((*CommentPlus)(nil), "pb.CommentPlus")
	proto.RegisterType((*CommentRecord)(nil), "pb.CommentRecord")
	proto.RegisterType((*MakeCommentReq)(nil), "pb.MakeCommentReq")
	proto.RegisterType((*MakeCommentRsp)(nil), "pb.MakeCommentRsp")
	proto.RegisterType((*UpNumCommentReq)(nil), "pb.UpNumCommentReq")
	proto.RegisterType((*UpNumCommentRsp)(nil), "pb.UpNumCommentRsp")
	proto.RegisterType((*MyCommentsReq)(nil), "pb.MyCommentsReq")
	proto.RegisterType((*MyCommentsRsp)(nil), "pb.MyCommentsRsp")
	proto.RegisterType((*MyComment)(nil), "pb.MyComment")
	proto.RegisterType((*DeleteCommentReq)(nil), "pb.DeleteCommentReq")
	proto.RegisterType((*DeleteCommentRsp)(nil), "pb.DeleteCommentRsp")
}

func init() { proto.RegisterFile("comment.ext.proto", fileDescriptor_b0f0800a31d81040) }

var fileDescriptor_b0f0800a31d81040 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x8b, 0x13, 0x3f,
	0x14, 0xfd, 0xa5, 0xff, 0xf6, 0xd7, 0x5b, 0xeb, 0x6e, 0xe3, 0x22, 0xc3, 0xe0, 0x43, 0x89, 0xc8,
	0xd6, 0x07, 0xab, 0xd4, 0x82, 0x20, 0x28, 0x88, 0x15, 0xac, 0xd0, 0x45, 0x22, 0xe2, 0xf3, 0x74,
	0x1a, 0xd7, 0xb0, 0x93, 0x99, 0x38, 0xc9, 0x2c, 0xeb, 0x37, 0xd2, 0x67, 0x3f, 0x83, 0xdf, 0x4b,
	0x92, 0x99, 0xce, 0x24, 0xb3, 0x7d, 0x10, 0x7d, 0x3c, 0xf7, 0xdc, 0x93, 0xb9, 0xf7, 0xe4, 0x4c,
	0x60, 0x12, 0x67, 0x42, 0xb0, 0x54, 0xcf, 0xd9, 0xb5, 0x9e, 0xcb, 0x3c, 0xd3, 0x19, 0xee, 0xc8,
	0x2d, 0x79, 0x08, 0xe3, 0xb7, 0x99, 0x7e, 0x5d, 0x72, 0x94, 0x7d, 0xc5, 0x01, 0x1c, 0x89, 0xec,
	0x8a, 0xb3, 0xf5, 0x2e, 0xe8, 0x4c, 0xd1, 0xac, 0x4b, 0xf7, 0x90, 0x2c, 0xbd, 0x56, 0x25, 0xf1,
	0x7d, 0xe8, 0xed, 0x22, 0x1d, 0x05, 0x68, 0x8a, 0x66, 0xa3, 0xc5, 0xf1, 0x5c, 0x6e, 0xe7, 0x15,
	0xbb, 0x8a, 0x74, 0x44, 0x2d, 0x49, 0x3e, 0xc1, 0xc8, 0x29, 0x1a, 0x8d, 0xe0, 0x29, 0x3f, 0xa0,
	0xd9, 0xf0, 0x94, 0x53, 0x4b, 0x9a, 0x26, 0x99, 0x14, 0xca, 0x0e, 0xe0, 0x37, 0xbd, 0x4f, 0x0a,
	0x45, 0x2d, 0x49, 0xde, 0xd5, 0x07, 0x1b, 0x25, 0x7e, 0x00, 0xbd, 0x84, 0x2b, 0x1d, 0xa0, 0x69,
	0x77, 0x36, 0x5a, 0x4c, 0x1c, 0x0d, 0x65, 0x71, 0x96, 0xef, 0xa8, 0xa5, 0xf1, 0x29, 0xf4, 0x75,
	0xa6, 0xa3, 0xa4, 0x5a, 0xae, 0x04, 0xce, 0x59, 0xe6, 0x03, 0xff, 0x76, 0xd6, 0x2f, 0x04, 0x63,
	0xaf, 0xdb, 0xf6, 0x71, 0x9d, 0x30, 0xbb, 0xf4, 0x90, 0x96, 0xc0, 0x18, 0x1d, 0x67, 0xa9, 0x66,
	0xa9, 0xb6, 0xfa, 0x21, 0xdd, 0x43, 0xc3, 0x7c, 0x61, 0xd1, 0x6e, 0x2d, 0x2e, 0x82, 0x6e, 0xc9,
	0x54, 0x10, 0x87, 0xf0, 0x7f, 0xca, 0xe3, 0xcb, 0x34, 0x12, 0x2c, 0xe8, 0x59, 0xaa, 0xc6, 0x86,
	0x8b, 0x73, 0x16, 0x69, 0xf6, 0x4a, 0x07, 0xfd, 0x92, 0xdb, 0x63, 0x33, 0x41, 0x21, 0xcf, 0x0b,
	0x11, 0x0c, 0xca, 0x49, 0x2d, 0xc0, 0xf7, 0x60, 0x58, 0x85, 0x62, 0xbd, 0x0a, 0x8e, 0x2c, 0xd3,
	0x14, 0xc8, 0x77, 0x04, 0xb7, 0x37, 0xd1, 0x25, 0x3b, 0x9c, 0x0d, 0xe4, 0x65, 0xa3, 0x59, 0xb1,
	0xd3, 0x5a, 0xf1, 0x2f, 0x16, 0xb9, 0x0b, 0x83, 0x42, 0xb1, 0x7c, 0xbd, 0xb3, 0x6b, 0x74, 0x69,
	0x85, 0x5c, 0xc3, 0x06, 0x9e, 0x61, 0xe4, 0xc4, 0x9f, 0x54, 0x49, 0xf2, 0x18, 0x8e, 0x3f, 0x9a,
	0x1d, 0x9d, 0xe1, 0xbd, 0x6d, 0x51, 0x7b, 0xdb, 0xb3, 0x96, 0x40, 0xc9, 0xc6, 0x34, 0xe4, 0x98,
	0x46, 0xce, 0x60, 0xbc, 0xf9, 0x56, 0x75, 0x29, 0x73, 0x6e, 0x33, 0x2e, 0x72, 0xc7, 0x25, 0x2f,
	0xbd, 0x46, 0x25, 0xf1, 0x23, 0x00, 0x51, 0x17, 0xaa, 0x6c, 0x8d, 0x4d, 0xb6, 0xea, 0x36, 0xea,
	0x34, 0x90, 0x1f, 0x08, 0x86, 0x35, 0x63, 0xa6, 0xff, 0xcc, 0x13, 0xb1, 0x16, 0xd1, 0xc5, 0x3e,
	0x47, 0x4d, 0xc1, 0xd8, 0x69, 0xc0, 0xb9, 0xb1, 0xb3, 0xbc, 0x81, 0x1a, 0x9b, 0x35, 0x54, 0x9c,
	0xe5, 0xac, 0xba, 0x82, 0x12, 0xf8, 0x6e, 0xf4, 0x5a, 0x6e, 0xb8, 0x56, 0xf7, 0xfd, 0x6c, 0x1e,
	0x4c, 0x12, 0x79, 0x02, 0x27, 0x2b, 0x96, 0x30, 0xcd, 0xfe, 0xd8, 0x6f, 0xdc, 0x56, 0x28, 0xb9,
	0xf8, 0xd9, 0x81, 0x49, 0x05, 0x3f, 0xb0, 0xfc, 0x8a, 0xc7, 0xec, 0xcd, 0xb5, 0xc6, 0x4b, 0x80,
	0xe6, 0xd9, 0xc1, 0xf6, 0x67, 0xf4, 0x5e, 0xac, 0xb0, 0x5d, 0x52, 0x92, 0xfc, 0x87, 0x9f, 0xc1,
	0xc8, 0x89, 0x04, 0xc6, 0xd6, 0x67, 0x2f, 0xcd, 0xe1, 0x8d, 0x9a, 0x15, 0x3e, 0x87, 0x5b, 0x6e,
	0x10, 0xf0, 0x1d, 0xd3, 0xd5, 0xca, 0x52, 0x78, 0xb3, 0x68, 0xb5, 0x4b, 0x80, 0xe6, 0xca, 0xcb,
	0x51, 0xbd, 0xac, 0x84, 0xed, 0x92, 0x55, 0xbd, 0x80, 0xb1, 0x67, 0x05, 0x3e, 0x35, 0x5d, 0x6d,
	0x3f, 0xc3, 0x03, 0x55, 0x23, 0xdf, 0x0e, 0xec, 0x63, 0xfe, 0xf4, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x79, 0xa3, 0x39, 0xbd, 0xe1, 0x05, 0x00, 0x00,
}
