// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: comment.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommentServiceExt service

type CommentServiceExtService interface {
	// 精彩影评
	HotComment(ctx context.Context, in *HotCommentReq, opts ...client.CallOption) (*HotCommentRsp, error)
	// 进行评论
	MakeComment(ctx context.Context, in *MakeCommentReq, opts ...client.CallOption) (*MakeCommentRsp, error)
	// 评论up
	UpNumComment(ctx context.Context, in *UpNumCommentReq, opts ...client.CallOption) (*UpNumCommentRsp, error)
	// 我的评论
	MyComments(ctx context.Context, in *MyCommentsReq, opts ...client.CallOption) (*MyCommentsRsp, error)
	// 删除评论
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...client.CallOption) (*DeleteCommentRsp, error)
}

type commentServiceExtService struct {
	c    client.Client
	name string
}

func NewCommentServiceExtService(name string, c client.Client) CommentServiceExtService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb"
	}
	return &commentServiceExtService{
		c:    c,
		name: name,
	}
}

func (c *commentServiceExtService) HotComment(ctx context.Context, in *HotCommentReq, opts ...client.CallOption) (*HotCommentRsp, error) {
	req := c.c.NewRequest(c.name, "CommentServiceExt.HotComment", in)
	out := new(HotCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceExtService) MakeComment(ctx context.Context, in *MakeCommentReq, opts ...client.CallOption) (*MakeCommentRsp, error) {
	req := c.c.NewRequest(c.name, "CommentServiceExt.MakeComment", in)
	out := new(MakeCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceExtService) UpNumComment(ctx context.Context, in *UpNumCommentReq, opts ...client.CallOption) (*UpNumCommentRsp, error) {
	req := c.c.NewRequest(c.name, "CommentServiceExt.UpNumComment", in)
	out := new(UpNumCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceExtService) MyComments(ctx context.Context, in *MyCommentsReq, opts ...client.CallOption) (*MyCommentsRsp, error) {
	req := c.c.NewRequest(c.name, "CommentServiceExt.MyComments", in)
	out := new(MyCommentsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceExtService) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...client.CallOption) (*DeleteCommentRsp, error) {
	req := c.c.NewRequest(c.name, "CommentServiceExt.DeleteComment", in)
	out := new(DeleteCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommentServiceExt service

type CommentServiceExtHandler interface {
	// 精彩影评
	HotComment(context.Context, *HotCommentReq, *HotCommentRsp) error
	// 进行评论
	MakeComment(context.Context, *MakeCommentReq, *MakeCommentRsp) error
	// 评论up
	UpNumComment(context.Context, *UpNumCommentReq, *UpNumCommentRsp) error
	// 我的评论
	MyComments(context.Context, *MyCommentsReq, *MyCommentsRsp) error
	// 删除评论
	DeleteComment(context.Context, *DeleteCommentReq, *DeleteCommentRsp) error
}

func RegisterCommentServiceExtHandler(s server.Server, hdlr CommentServiceExtHandler, opts ...server.HandlerOption) error {
	type commentServiceExt interface {
		HotComment(ctx context.Context, in *HotCommentReq, out *HotCommentRsp) error
		MakeComment(ctx context.Context, in *MakeCommentReq, out *MakeCommentRsp) error
		UpNumComment(ctx context.Context, in *UpNumCommentReq, out *UpNumCommentRsp) error
		MyComments(ctx context.Context, in *MyCommentsReq, out *MyCommentsRsp) error
		DeleteComment(ctx context.Context, in *DeleteCommentReq, out *DeleteCommentRsp) error
	}
	type CommentServiceExt struct {
		commentServiceExt
	}
	h := &commentServiceExtHandler{hdlr}
	return s.Handle(s.NewHandler(&CommentServiceExt{h}, opts...))
}

type commentServiceExtHandler struct {
	CommentServiceExtHandler
}

func (h *commentServiceExtHandler) HotComment(ctx context.Context, in *HotCommentReq, out *HotCommentRsp) error {
	return h.CommentServiceExtHandler.HotComment(ctx, in, out)
}

func (h *commentServiceExtHandler) MakeComment(ctx context.Context, in *MakeCommentReq, out *MakeCommentRsp) error {
	return h.CommentServiceExtHandler.MakeComment(ctx, in, out)
}

func (h *commentServiceExtHandler) UpNumComment(ctx context.Context, in *UpNumCommentReq, out *UpNumCommentRsp) error {
	return h.CommentServiceExtHandler.UpNumComment(ctx, in, out)
}

func (h *commentServiceExtHandler) MyComments(ctx context.Context, in *MyCommentsReq, out *MyCommentsRsp) error {
	return h.CommentServiceExtHandler.MyComments(ctx, in, out)
}

func (h *commentServiceExtHandler) DeleteComment(ctx context.Context, in *DeleteCommentReq, out *DeleteCommentRsp) error {
	return h.CommentServiceExtHandler.DeleteComment(ctx, in, out)
}
