// Code generated by protoc-gen-go. DO NOT EDIT.
// source: film.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotPlayMoviesReq struct {
	Location             int64    `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotPlayMoviesReq) Reset()         { *m = HotPlayMoviesReq{} }
func (m *HotPlayMoviesReq) String() string { return proto.CompactTextString(m) }
func (*HotPlayMoviesReq) ProtoMessage()    {}
func (*HotPlayMoviesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{0}
}

func (m *HotPlayMoviesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotPlayMoviesReq.Unmarshal(m, b)
}
func (m *HotPlayMoviesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotPlayMoviesReq.Marshal(b, m, deterministic)
}
func (m *HotPlayMoviesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotPlayMoviesReq.Merge(m, src)
}
func (m *HotPlayMoviesReq) XXX_Size() int {
	return xxx_messageInfo_HotPlayMoviesReq.Size(m)
}
func (m *HotPlayMoviesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HotPlayMoviesReq.DiscardUnknown(m)
}

var xxx_messageInfo_HotPlayMoviesReq proto.InternalMessageInfo

func (m *HotPlayMoviesReq) GetLocation() int64 {
	if m != nil {
		return m.Location
	}
	return 0
}

type HotPlayMoviesRep struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotPlayMoviesRep) Reset()         { *m = HotPlayMoviesRep{} }
func (m *HotPlayMoviesRep) String() string { return proto.CompactTextString(m) }
func (*HotPlayMoviesRep) ProtoMessage()    {}
func (*HotPlayMoviesRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{1}
}

func (m *HotPlayMoviesRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotPlayMoviesRep.Unmarshal(m, b)
}
func (m *HotPlayMoviesRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotPlayMoviesRep.Marshal(b, m, deterministic)
}
func (m *HotPlayMoviesRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotPlayMoviesRep.Merge(m, src)
}
func (m *HotPlayMoviesRep) XXX_Size() int {
	return xxx_messageInfo_HotPlayMoviesRep.Size(m)
}
func (m *HotPlayMoviesRep) XXX_DiscardUnknown() {
	xxx_messageInfo_HotPlayMoviesRep.DiscardUnknown(m)
}

var xxx_messageInfo_HotPlayMoviesRep proto.InternalMessageInfo

func (m *HotPlayMoviesRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type Movie struct {
	Img                  string   `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	TitleCn              string   `protobuf:"bytes,3,opt,name=titleCn,proto3" json:"titleCn,omitempty"`
	MovieSupportType     string   `protobuf:"bytes,4,opt,name=movieSupportType,proto3" json:"movieSupportType,omitempty"`
	FilmDirector         string   `protobuf:"bytes,5,opt,name=filmDirector,proto3" json:"filmDirector,omitempty"`
	Actors               string   `protobuf:"bytes,6,opt,name=actors,proto3" json:"actors,omitempty"`
	FilmDrama            string   `protobuf:"bytes,7,opt,name=filmDrama,proto3" json:"filmDrama,omitempty"`
	RatingFinal          float32  `protobuf:"fixed32,8,opt,name=ratingFinal,proto3" json:"ratingFinal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{2}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *Movie) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *Movie) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *Movie) GetMovieSupportType() string {
	if m != nil {
		return m.MovieSupportType
	}
	return ""
}

func (m *Movie) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *Movie) GetActors() string {
	if m != nil {
		return m.Actors
	}
	return ""
}

func (m *Movie) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *Movie) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

type HotMovie struct {
	ActorName            []string `protobuf:"bytes,1,rep,name=actorName,proto3" json:"actorName,omitempty"`
	CommonSpecial        string   `protobuf:"bytes,2,opt,name=commonSpecial,proto3" json:"commonSpecial,omitempty"`
	DirectorName         string   `protobuf:"bytes,3,opt,name=directorName,proto3" json:"directorName,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	Is3D                 int64    `protobuf:"varint,5,opt,name=is3D,proto3" json:"is3D,omitempty"`
	IsDMAX               int64    `protobuf:"varint,6,opt,name=isDMAX,proto3" json:"isDMAX,omitempty"`
	IsFilter             int64    `protobuf:"varint,7,opt,name=isFilter,proto3" json:"isFilter,omitempty"`
	IsHot                int64    `protobuf:"varint,8,opt,name=isHot,proto3" json:"isHot,omitempty"`
	IsIMAX               int64    `protobuf:"varint,9,opt,name=isIMAX,proto3" json:"isIMAX,omitempty"`
	IsIMAX3D             int64    `protobuf:"varint,10,opt,name=isIMAX3D,proto3" json:"isIMAX3D,omitempty"`
	IsNew                int64    `protobuf:"varint,11,opt,name=isNew,proto3" json:"isNew,omitempty"`
	Length               int64    `protobuf:"varint,12,opt,name=length,proto3" json:"length,omitempty"`
	MovieId              int64    `protobuf:"varint,13,opt,name=movieId,proto3" json:"movieId,omitempty"`
	RDay                 int64    `protobuf:"varint,14,opt,name=rDay,proto3" json:"rDay,omitempty"`
	RMonth               int64    `protobuf:"varint,15,opt,name=rMonth,proto3" json:"rMonth,omitempty"`
	RYear                int64    `protobuf:"varint,16,opt,name=rYear,proto3" json:"rYear,omitempty"`
	RatingFinal          float32  `protobuf:"fixed32,17,opt,name=ratingFinal,proto3" json:"ratingFinal,omitempty"`
	T                    string   `protobuf:"bytes,18,opt,name=t,proto3" json:"t,omitempty"`
	TitleCn              string   `protobuf:"bytes,19,opt,name=titleCn,proto3" json:"titleCn,omitempty"`
	TitleEn              string   `protobuf:"bytes,20,opt,name=titleEn,proto3" json:"titleEn,omitempty"`
	Type                 string   `protobuf:"bytes,21,opt,name=type,proto3" json:"type,omitempty"`
	WantedCount          int64    `protobuf:"varint,22,opt,name=wantedCount,proto3" json:"wantedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotMovie) Reset()         { *m = HotMovie{} }
func (m *HotMovie) String() string { return proto.CompactTextString(m) }
func (*HotMovie) ProtoMessage()    {}
func (*HotMovie) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{3}
}

func (m *HotMovie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotMovie.Unmarshal(m, b)
}
func (m *HotMovie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotMovie.Marshal(b, m, deterministic)
}
func (m *HotMovie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotMovie.Merge(m, src)
}
func (m *HotMovie) XXX_Size() int {
	return xxx_messageInfo_HotMovie.Size(m)
}
func (m *HotMovie) XXX_DiscardUnknown() {
	xxx_messageInfo_HotMovie.DiscardUnknown(m)
}

var xxx_messageInfo_HotMovie proto.InternalMessageInfo

func (m *HotMovie) GetActorName() []string {
	if m != nil {
		return m.ActorName
	}
	return nil
}

func (m *HotMovie) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *HotMovie) GetDirectorName() string {
	if m != nil {
		return m.DirectorName
	}
	return ""
}

func (m *HotMovie) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *HotMovie) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *HotMovie) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *HotMovie) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *HotMovie) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *HotMovie) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *HotMovie) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *HotMovie) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *HotMovie) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *HotMovie) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *HotMovie) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *HotMovie) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *HotMovie) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *HotMovie) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

func (m *HotMovie) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

func (m *HotMovie) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *HotMovie) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *HotMovie) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HotMovie) GetWantedCount() int64 {
	if m != nil {
		return m.WantedCount
	}
	return 0
}

type FilmAllMessage struct {
	Logo                 string   `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	FilmLong             int64    `protobuf:"varint,2,opt,name=filmLong,proto3" json:"filmLong,omitempty"`
	IsSelectSeat         int64    `protobuf:"varint,3,opt,name=isSelectSeat,proto3" json:"isSelectSeat,omitempty"`
	FilmPrice            float32  `protobuf:"fixed32,4,opt,name=filmPrice,proto3" json:"filmPrice,omitempty"`
	FilmScreenwriter     string   `protobuf:"bytes,5,opt,name=filmScreenwriter,proto3" json:"filmScreenwriter,omitempty"`
	CommentNum           int64    `protobuf:"varint,6,opt,name=commentNum,proto3" json:"commentNum,omitempty"`
	FilmName             string   `protobuf:"bytes,7,opt,name=filmName,proto3" json:"filmName,omitempty"`
	IsSupportInlineWatch int64    `protobuf:"varint,8,opt,name=isSupportInlineWatch,proto3" json:"isSupportInlineWatch,omitempty"`
	CreateAt             string   `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`
	BigType              int64    `protobuf:"varint,10,opt,name=bigType,proto3" json:"bigType,omitempty"`
	FilmDrama            string   `protobuf:"bytes,11,opt,name=filmDrama,proto3" json:"filmDrama,omitempty"`
	UserAccessTimes      int64    `protobuf:"varint,12,opt,name=userAccessTimes,proto3" json:"userAccessTimes,omitempty"`
	FilmBoxoffice        float32  `protobuf:"fixed32,13,opt,name=filmBoxoffice,proto3" json:"filmBoxoffice,omitempty"`
	FilmDirector         string   `protobuf:"bytes,14,opt,name=filmDirector,proto3" json:"filmDirector,omitempty"`
	UserLikeWatchTimes   int64    `protobuf:"varint,15,opt,name=userLikeWatchTimes,proto3" json:"userLikeWatchTimes,omitempty"`
	UserCommentTimes     int64    `protobuf:"varint,16,opt,name=userCommentTimes,proto3" json:"userCommentTimes,omitempty"`
	CompanyIssued        string   `protobuf:"bytes,17,opt,name=companyIssued,proto3" json:"companyIssued,omitempty"`
	Country              string   `protobuf:"bytes,18,opt,name=country,proto3" json:"country,omitempty"`
	CommentScore         float32  `protobuf:"fixed32,19,opt,name=commentScore,proto3" json:"commentScore,omitempty"`
	Is3D                 int64    `protobuf:"varint,20,opt,name=is3D,proto3" json:"is3D,omitempty"`
	IsDMAX               int64    `protobuf:"varint,21,opt,name=isDMAX,proto3" json:"isDMAX,omitempty"`
	IsFilter             int64    `protobuf:"varint,22,opt,name=isFilter,proto3" json:"isFilter,omitempty"`
	IsHot                int64    `protobuf:"varint,23,opt,name=isHot,proto3" json:"isHot,omitempty"`
	IsIMAX               int64    `protobuf:"varint,24,opt,name=isIMAX,proto3" json:"isIMAX,omitempty"`
	IsIMAX3D             int64    `protobuf:"varint,25,opt,name=isIMAX3D,proto3" json:"isIMAX3D,omitempty"`
	IsNew                int64    `protobuf:"varint,26,opt,name=isNew,proto3" json:"isNew,omitempty"`
	RDay                 int64    `protobuf:"varint,27,opt,name=rDay,proto3" json:"rDay,omitempty"`
	RMonth               int64    `protobuf:"varint,28,opt,name=rMonth,proto3" json:"rMonth,omitempty"`
	RYear                int64    `protobuf:"varint,29,opt,name=rYear,proto3" json:"rYear,omitempty"`
	CommonSpecial        string   `protobuf:"bytes,30,opt,name=commonSpecial,proto3" json:"commonSpecial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilmAllMessage) Reset()         { *m = FilmAllMessage{} }
func (m *FilmAllMessage) String() string { return proto.CompactTextString(m) }
func (*FilmAllMessage) ProtoMessage()    {}
func (*FilmAllMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{4}
}

func (m *FilmAllMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilmAllMessage.Unmarshal(m, b)
}
func (m *FilmAllMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilmAllMessage.Marshal(b, m, deterministic)
}
func (m *FilmAllMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilmAllMessage.Merge(m, src)
}
func (m *FilmAllMessage) XXX_Size() int {
	return xxx_messageInfo_FilmAllMessage.Size(m)
}
func (m *FilmAllMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FilmAllMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FilmAllMessage proto.InternalMessageInfo

func (m *FilmAllMessage) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *FilmAllMessage) GetFilmLong() int64 {
	if m != nil {
		return m.FilmLong
	}
	return 0
}

func (m *FilmAllMessage) GetIsSelectSeat() int64 {
	if m != nil {
		return m.IsSelectSeat
	}
	return 0
}

func (m *FilmAllMessage) GetFilmPrice() float32 {
	if m != nil {
		return m.FilmPrice
	}
	return 0
}

func (m *FilmAllMessage) GetFilmScreenwriter() string {
	if m != nil {
		return m.FilmScreenwriter
	}
	return ""
}

func (m *FilmAllMessage) GetCommentNum() int64 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *FilmAllMessage) GetFilmName() string {
	if m != nil {
		return m.FilmName
	}
	return ""
}

func (m *FilmAllMessage) GetIsSupportInlineWatch() int64 {
	if m != nil {
		return m.IsSupportInlineWatch
	}
	return 0
}

func (m *FilmAllMessage) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *FilmAllMessage) GetBigType() int64 {
	if m != nil {
		return m.BigType
	}
	return 0
}

func (m *FilmAllMessage) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *FilmAllMessage) GetUserAccessTimes() int64 {
	if m != nil {
		return m.UserAccessTimes
	}
	return 0
}

func (m *FilmAllMessage) GetFilmBoxoffice() float32 {
	if m != nil {
		return m.FilmBoxoffice
	}
	return 0
}

func (m *FilmAllMessage) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *FilmAllMessage) GetUserLikeWatchTimes() int64 {
	if m != nil {
		return m.UserLikeWatchTimes
	}
	return 0
}

func (m *FilmAllMessage) GetUserCommentTimes() int64 {
	if m != nil {
		return m.UserCommentTimes
	}
	return 0
}

func (m *FilmAllMessage) GetCompanyIssued() string {
	if m != nil {
		return m.CompanyIssued
	}
	return ""
}

func (m *FilmAllMessage) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *FilmAllMessage) GetCommentScore() float32 {
	if m != nil {
		return m.CommentScore
	}
	return 0
}

func (m *FilmAllMessage) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *FilmAllMessage) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *FilmAllMessage) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *FilmAllMessage) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *FilmAllMessage) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *FilmAllMessage) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *FilmAllMessage) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *FilmAllMessage) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *FilmAllMessage) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *FilmAllMessage) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *FilmAllMessage) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

type MovieDetailReq struct {
	LocationId           int64    `protobuf:"varint,1,opt,name=locationId,proto3" json:"locationId,omitempty"`
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieDetailReq) Reset()         { *m = MovieDetailReq{} }
func (m *MovieDetailReq) String() string { return proto.CompactTextString(m) }
func (*MovieDetailReq) ProtoMessage()    {}
func (*MovieDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{5}
}

func (m *MovieDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieDetailReq.Unmarshal(m, b)
}
func (m *MovieDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieDetailReq.Marshal(b, m, deterministic)
}
func (m *MovieDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieDetailReq.Merge(m, src)
}
func (m *MovieDetailReq) XXX_Size() int {
	return xxx_messageInfo_MovieDetailReq.Size(m)
}
func (m *MovieDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_MovieDetailReq proto.InternalMessageInfo

func (m *MovieDetailReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *MovieDetailReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type MovieDetailRep struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	TitleCn              string   `protobuf:"bytes,2,opt,name=titleCn,proto3" json:"titleCn,omitempty"`
	TitleEn              string   `protobuf:"bytes,3,opt,name=titleEn,proto3" json:"titleEn,omitempty"`
	Rating               float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Year                 int64    `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	RunTime              int64    `protobuf:"varint,8,opt,name=runTime,proto3" json:"runTime,omitempty"`
	CommonSpecial        string   `protobuf:"bytes,9,opt,name=commonSpecial,proto3" json:"commonSpecial,omitempty"`
	Director             string   `protobuf:"bytes,10,opt,name=director,proto3" json:"director,omitempty"`
	Release              *Release `protobuf:"bytes,11,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieDetailRep) Reset()         { *m = MovieDetailRep{} }
func (m *MovieDetailRep) String() string { return proto.CompactTextString(m) }
func (*MovieDetailRep) ProtoMessage()    {}
func (*MovieDetailRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{6}
}

func (m *MovieDetailRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieDetailRep.Unmarshal(m, b)
}
func (m *MovieDetailRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieDetailRep.Marshal(b, m, deterministic)
}
func (m *MovieDetailRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieDetailRep.Merge(m, src)
}
func (m *MovieDetailRep) XXX_Size() int {
	return xxx_messageInfo_MovieDetailRep.Size(m)
}
func (m *MovieDetailRep) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieDetailRep.DiscardUnknown(m)
}

var xxx_messageInfo_MovieDetailRep proto.InternalMessageInfo

func (m *MovieDetailRep) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MovieDetailRep) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *MovieDetailRep) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *MovieDetailRep) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MovieDetailRep) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *MovieDetailRep) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MovieDetailRep) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MovieDetailRep) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *MovieDetailRep) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *MovieDetailRep) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *MovieDetailRep) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type Release struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{7}
}

func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (m *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(m, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Release) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type MovieCreditsWithTypesReq struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=MovieId,proto3" json:"MovieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieCreditsWithTypesReq) Reset()         { *m = MovieCreditsWithTypesReq{} }
func (m *MovieCreditsWithTypesReq) String() string { return proto.CompactTextString(m) }
func (*MovieCreditsWithTypesReq) ProtoMessage()    {}
func (*MovieCreditsWithTypesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{8}
}

func (m *MovieCreditsWithTypesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieCreditsWithTypesReq.Unmarshal(m, b)
}
func (m *MovieCreditsWithTypesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieCreditsWithTypesReq.Marshal(b, m, deterministic)
}
func (m *MovieCreditsWithTypesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieCreditsWithTypesReq.Merge(m, src)
}
func (m *MovieCreditsWithTypesReq) XXX_Size() int {
	return xxx_messageInfo_MovieCreditsWithTypesReq.Size(m)
}
func (m *MovieCreditsWithTypesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieCreditsWithTypesReq.DiscardUnknown(m)
}

var xxx_messageInfo_MovieCreditsWithTypesReq proto.InternalMessageInfo

func (m *MovieCreditsWithTypesReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type MovieCreditsWithTypesRep struct {
	Types                []*Type  `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieCreditsWithTypesRep) Reset()         { *m = MovieCreditsWithTypesRep{} }
func (m *MovieCreditsWithTypesRep) String() string { return proto.CompactTextString(m) }
func (*MovieCreditsWithTypesRep) ProtoMessage()    {}
func (*MovieCreditsWithTypesRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{9}
}

func (m *MovieCreditsWithTypesRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieCreditsWithTypesRep.Unmarshal(m, b)
}
func (m *MovieCreditsWithTypesRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieCreditsWithTypesRep.Marshal(b, m, deterministic)
}
func (m *MovieCreditsWithTypesRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieCreditsWithTypesRep.Merge(m, src)
}
func (m *MovieCreditsWithTypesRep) XXX_Size() int {
	return xxx_messageInfo_MovieCreditsWithTypesRep.Size(m)
}
func (m *MovieCreditsWithTypesRep) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieCreditsWithTypesRep.DiscardUnknown(m)
}

var xxx_messageInfo_MovieCreditsWithTypesRep proto.InternalMessageInfo

func (m *MovieCreditsWithTypesRep) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

type Type struct {
	TypeName             string     `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	TypeNameEc           string     `protobuf:"bytes,2,opt,name=typeNameEc,proto3" json:"typeNameEc,omitempty"`
	Persons              []*Persons `protobuf:"bytes,3,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{10}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Type) GetTypeNameEc() string {
	if m != nil {
		return m.TypeNameEc
	}
	return ""
}

func (m *Type) GetPersons() []*Persons {
	if m != nil {
		return m.Persons
	}
	return nil
}

type Persons struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn               string   `protobuf:"bytes,3,opt,name=nameEn,proto3" json:"nameEn,omitempty"`
	RoleCover            string   `protobuf:"bytes,4,opt,name=roleCover,proto3" json:"roleCover,omitempty"`
	Personate            string   `protobuf:"bytes,5,opt,name=personate,proto3" json:"personate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Persons) Reset()         { *m = Persons{} }
func (m *Persons) String() string { return proto.CompactTextString(m) }
func (*Persons) ProtoMessage()    {}
func (*Persons) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{11}
}

func (m *Persons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persons.Unmarshal(m, b)
}
func (m *Persons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persons.Marshal(b, m, deterministic)
}
func (m *Persons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persons.Merge(m, src)
}
func (m *Persons) XXX_Size() int {
	return xxx_messageInfo_Persons.Size(m)
}
func (m *Persons) XXX_DiscardUnknown() {
	xxx_messageInfo_Persons.DiscardUnknown(m)
}

var xxx_messageInfo_Persons proto.InternalMessageInfo

func (m *Persons) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Persons) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Persons) GetNameEn() string {
	if m != nil {
		return m.NameEn
	}
	return ""
}

func (m *Persons) GetRoleCover() string {
	if m != nil {
		return m.RoleCover
	}
	return ""
}

func (m *Persons) GetPersonate() string {
	if m != nil {
		return m.Personate
	}
	return ""
}

type ImageAllReq struct {
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageAllReq) Reset()         { *m = ImageAllReq{} }
func (m *ImageAllReq) String() string { return proto.CompactTextString(m) }
func (*ImageAllReq) ProtoMessage()    {}
func (*ImageAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{12}
}

func (m *ImageAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageAllReq.Unmarshal(m, b)
}
func (m *ImageAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageAllReq.Marshal(b, m, deterministic)
}
func (m *ImageAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageAllReq.Merge(m, src)
}
func (m *ImageAllReq) XXX_Size() int {
	return xxx_messageInfo_ImageAllReq.Size(m)
}
func (m *ImageAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImageAllReq proto.InternalMessageInfo

func (m *ImageAllReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type ImageAllRep struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageAllRep) Reset()         { *m = ImageAllRep{} }
func (m *ImageAllRep) String() string { return proto.CompactTextString(m) }
func (*ImageAllRep) ProtoMessage()    {}
func (*ImageAllRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{13}
}

func (m *ImageAllRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageAllRep.Unmarshal(m, b)
}
func (m *ImageAllRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageAllRep.Marshal(b, m, deterministic)
}
func (m *ImageAllRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageAllRep.Merge(m, src)
}
func (m *ImageAllRep) XXX_Size() int {
	return xxx_messageInfo_ImageAllRep.Size(m)
}
func (m *ImageAllRep) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageAllRep.DiscardUnknown(m)
}

var xxx_messageInfo_ImageAllRep proto.InternalMessageInfo

func (m *ImageAllRep) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Image struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{14}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type LocationMoviesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationMoviesReq) Reset()         { *m = LocationMoviesReq{} }
func (m *LocationMoviesReq) String() string { return proto.CompactTextString(m) }
func (*LocationMoviesReq) ProtoMessage()    {}
func (*LocationMoviesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{15}
}

func (m *LocationMoviesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationMoviesReq.Unmarshal(m, b)
}
func (m *LocationMoviesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationMoviesReq.Marshal(b, m, deterministic)
}
func (m *LocationMoviesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationMoviesReq.Merge(m, src)
}
func (m *LocationMoviesReq) XXX_Size() int {
	return xxx_messageInfo_LocationMoviesReq.Size(m)
}
func (m *LocationMoviesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationMoviesReq.DiscardUnknown(m)
}

var xxx_messageInfo_LocationMoviesReq proto.InternalMessageInfo

type LocationMoviesRep struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationMoviesRep) Reset()         { *m = LocationMoviesRep{} }
func (m *LocationMoviesRep) String() string { return proto.CompactTextString(m) }
func (*LocationMoviesRep) ProtoMessage()    {}
func (*LocationMoviesRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{16}
}

func (m *LocationMoviesRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationMoviesRep.Unmarshal(m, b)
}
func (m *LocationMoviesRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationMoviesRep.Marshal(b, m, deterministic)
}
func (m *LocationMoviesRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationMoviesRep.Merge(m, src)
}
func (m *LocationMoviesRep) XXX_Size() int {
	return xxx_messageInfo_LocationMoviesRep.Size(m)
}
func (m *LocationMoviesRep) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationMoviesRep.DiscardUnknown(m)
}

var xxx_messageInfo_LocationMoviesRep proto.InternalMessageInfo

func (m *LocationMoviesRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type MovieComingNewReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieComingNewReq) Reset()         { *m = MovieComingNewReq{} }
func (m *MovieComingNewReq) String() string { return proto.CompactTextString(m) }
func (*MovieComingNewReq) ProtoMessage()    {}
func (*MovieComingNewReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{17}
}

func (m *MovieComingNewReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieComingNewReq.Unmarshal(m, b)
}
func (m *MovieComingNewReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieComingNewReq.Marshal(b, m, deterministic)
}
func (m *MovieComingNewReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieComingNewReq.Merge(m, src)
}
func (m *MovieComingNewReq) XXX_Size() int {
	return xxx_messageInfo_MovieComingNewReq.Size(m)
}
func (m *MovieComingNewReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieComingNewReq.DiscardUnknown(m)
}

var xxx_messageInfo_MovieComingNewReq proto.InternalMessageInfo

type MovieComingNewRep struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieComingNewRep) Reset()         { *m = MovieComingNewRep{} }
func (m *MovieComingNewRep) String() string { return proto.CompactTextString(m) }
func (*MovieComingNewRep) ProtoMessage()    {}
func (*MovieComingNewRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{18}
}

func (m *MovieComingNewRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieComingNewRep.Unmarshal(m, b)
}
func (m *MovieComingNewRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieComingNewRep.Marshal(b, m, deterministic)
}
func (m *MovieComingNewRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieComingNewRep.Merge(m, src)
}
func (m *MovieComingNewRep) XXX_Size() int {
	return xxx_messageInfo_MovieComingNewRep.Size(m)
}
func (m *MovieComingNewRep) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieComingNewRep.DiscardUnknown(m)
}

var xxx_messageInfo_MovieComingNewRep proto.InternalMessageInfo

func (m *MovieComingNewRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type SearchRep struct {
	Subjects             []*SearchMovie `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchRep) Reset()         { *m = SearchRep{} }
func (m *SearchRep) String() string { return proto.CompactTextString(m) }
func (*SearchRep) ProtoMessage()    {}
func (*SearchRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{19}
}

func (m *SearchRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRep.Unmarshal(m, b)
}
func (m *SearchRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRep.Marshal(b, m, deterministic)
}
func (m *SearchRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRep.Merge(m, src)
}
func (m *SearchRep) XXX_Size() int {
	return xxx_messageInfo_SearchRep.Size(m)
}
func (m *SearchRep) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRep.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRep proto.InternalMessageInfo

func (m *SearchRep) GetSubjects() []*SearchMovie {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *SearchRep) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SearchReq struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{20}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type SearchMovie struct {
	Title                string    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Id                   string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Image                *Images   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Genres               []*Genres `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Year                 string    `protobuf:"bytes,5,opt,name=year,proto3" json:"year,omitempty"`
	Rating               *Rating   `protobuf:"bytes,6,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchMovie) Reset()         { *m = SearchMovie{} }
func (m *SearchMovie) String() string { return proto.CompactTextString(m) }
func (*SearchMovie) ProtoMessage()    {}
func (*SearchMovie) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{21}
}

func (m *SearchMovie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMovie.Unmarshal(m, b)
}
func (m *SearchMovie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMovie.Marshal(b, m, deterministic)
}
func (m *SearchMovie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMovie.Merge(m, src)
}
func (m *SearchMovie) XXX_Size() int {
	return xxx_messageInfo_SearchMovie.Size(m)
}
func (m *SearchMovie) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMovie.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMovie proto.InternalMessageInfo

func (m *SearchMovie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchMovie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchMovie) GetImage() *Images {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *SearchMovie) GetGenres() []*Genres {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *SearchMovie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *SearchMovie) GetRating() *Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type Genres struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genres) Reset()         { *m = Genres{} }
func (m *Genres) String() string { return proto.CompactTextString(m) }
func (*Genres) ProtoMessage()    {}
func (*Genres) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{22}
}

func (m *Genres) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genres.Unmarshal(m, b)
}
func (m *Genres) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genres.Marshal(b, m, deterministic)
}
func (m *Genres) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genres.Merge(m, src)
}
func (m *Genres) XXX_Size() int {
	return xxx_messageInfo_Genres.Size(m)
}
func (m *Genres) XXX_DiscardUnknown() {
	xxx_messageInfo_Genres.DiscardUnknown(m)
}

var xxx_messageInfo_Genres proto.InternalMessageInfo

func (m *Genres) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Rating struct {
	Average              float32  `protobuf:"fixed32,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{23}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetAverage() float32 {
	if m != nil {
		return m.Average
	}
	return 0
}

type Images struct {
	Small                string   `protobuf:"bytes,1,opt,name=small,proto3" json:"small,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Images) Reset()         { *m = Images{} }
func (m *Images) String() string { return proto.CompactTextString(m) }
func (*Images) ProtoMessage()    {}
func (*Images) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{24}
}

func (m *Images) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Images.Unmarshal(m, b)
}
func (m *Images) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Images.Marshal(b, m, deterministic)
}
func (m *Images) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Images.Merge(m, src)
}
func (m *Images) XXX_Size() int {
	return xxx_messageInfo_Images.Size(m)
}
func (m *Images) XXX_DiscardUnknown() {
	xxx_messageInfo_Images.DiscardUnknown(m)
}

var xxx_messageInfo_Images proto.InternalMessageInfo

func (m *Images) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

type DayMovie struct {
	ReleaseTime          string   `protobuf:"bytes,1,opt,name=releaseTime,proto3" json:"releaseTime,omitempty"`
	Length               int64    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ReleaseType          string   `protobuf:"bytes,3,opt,name=releaseType,proto3" json:"releaseType,omitempty"`
	MhName               string   `protobuf:"bytes,4,opt,name=mhName,proto3" json:"mhName,omitempty"`
	ReleaseDiscount      float32  `protobuf:"fixed32,5,opt,name=releaseDiscount,proto3" json:"releaseDiscount,omitempty"`
	MovieId              int64    `protobuf:"varint,6,opt,name=movieId,proto3" json:"movieId,omitempty"`
	MhId                 int64    `protobuf:"varint,7,opt,name=mhId,proto3" json:"mhId,omitempty"`
	CinemaId             int64    `protobuf:"varint,8,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	FilmName             string   `protobuf:"bytes,9,opt,name=filmName,proto3" json:"filmName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DayMovie) Reset()         { *m = DayMovie{} }
func (m *DayMovie) String() string { return proto.CompactTextString(m) }
func (*DayMovie) ProtoMessage()    {}
func (*DayMovie) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{25}
}

func (m *DayMovie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayMovie.Unmarshal(m, b)
}
func (m *DayMovie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayMovie.Marshal(b, m, deterministic)
}
func (m *DayMovie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayMovie.Merge(m, src)
}
func (m *DayMovie) XXX_Size() int {
	return xxx_messageInfo_DayMovie.Size(m)
}
func (m *DayMovie) XXX_DiscardUnknown() {
	xxx_messageInfo_DayMovie.DiscardUnknown(m)
}

var xxx_messageInfo_DayMovie proto.InternalMessageInfo

func (m *DayMovie) GetReleaseTime() string {
	if m != nil {
		return m.ReleaseTime
	}
	return ""
}

func (m *DayMovie) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *DayMovie) GetReleaseType() string {
	if m != nil {
		return m.ReleaseType
	}
	return ""
}

func (m *DayMovie) GetMhName() string {
	if m != nil {
		return m.MhName
	}
	return ""
}

func (m *DayMovie) GetReleaseDiscount() float32 {
	if m != nil {
		return m.ReleaseDiscount
	}
	return 0
}

func (m *DayMovie) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *DayMovie) GetMhId() int64 {
	if m != nil {
		return m.MhId
	}
	return 0
}

func (m *DayMovie) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

func (m *DayMovie) GetFilmName() string {
	if m != nil {
		return m.FilmName
	}
	return ""
}

type GetFilmsByCidADayReq struct {
	CinemaId             int64    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	FilmId               int64    `protobuf:"varint,2,opt,name=filmId,proto3" json:"filmId,omitempty"`
	DayNum               int64    `protobuf:"varint,3,opt,name=dayNum,proto3" json:"dayNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilmsByCidADayReq) Reset()         { *m = GetFilmsByCidADayReq{} }
func (m *GetFilmsByCidADayReq) String() string { return proto.CompactTextString(m) }
func (*GetFilmsByCidADayReq) ProtoMessage()    {}
func (*GetFilmsByCidADayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{26}
}

func (m *GetFilmsByCidADayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilmsByCidADayReq.Unmarshal(m, b)
}
func (m *GetFilmsByCidADayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilmsByCidADayReq.Marshal(b, m, deterministic)
}
func (m *GetFilmsByCidADayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilmsByCidADayReq.Merge(m, src)
}
func (m *GetFilmsByCidADayReq) XXX_Size() int {
	return xxx_messageInfo_GetFilmsByCidADayReq.Size(m)
}
func (m *GetFilmsByCidADayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilmsByCidADayReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilmsByCidADayReq proto.InternalMessageInfo

func (m *GetFilmsByCidADayReq) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

func (m *GetFilmsByCidADayReq) GetFilmId() int64 {
	if m != nil {
		return m.FilmId
	}
	return 0
}

func (m *GetFilmsByCidADayReq) GetDayNum() int64 {
	if m != nil {
		return m.DayNum
	}
	return 0
}

type GetFilmsByCidADayRsp struct {
	DayMovie             []*DayMovie `protobuf:"bytes,1,rep,name=dayMovie,proto3" json:"dayMovie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFilmsByCidADayRsp) Reset()         { *m = GetFilmsByCidADayRsp{} }
func (m *GetFilmsByCidADayRsp) String() string { return proto.CompactTextString(m) }
func (*GetFilmsByCidADayRsp) ProtoMessage()    {}
func (*GetFilmsByCidADayRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713d3e051ba96f1, []int{27}
}

func (m *GetFilmsByCidADayRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilmsByCidADayRsp.Unmarshal(m, b)
}
func (m *GetFilmsByCidADayRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilmsByCidADayRsp.Marshal(b, m, deterministic)
}
func (m *GetFilmsByCidADayRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilmsByCidADayRsp.Merge(m, src)
}
func (m *GetFilmsByCidADayRsp) XXX_Size() int {
	return xxx_messageInfo_GetFilmsByCidADayRsp.Size(m)
}
func (m *GetFilmsByCidADayRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilmsByCidADayRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilmsByCidADayRsp proto.InternalMessageInfo

func (m *GetFilmsByCidADayRsp) GetDayMovie() []*DayMovie {
	if m != nil {
		return m.DayMovie
	}
	return nil
}

func init() {
	proto.RegisterType((*HotPlayMoviesReq)(nil), "pb.HotPlayMoviesReq")
	proto.RegisterType((*HotPlayMoviesRep)(nil), "pb.HotPlayMoviesRep")
	proto.RegisterType((*Movie)(nil), "pb.Movie")
	proto.RegisterType((*HotMovie)(nil), "pb.HotMovie")
	proto.RegisterType((*FilmAllMessage)(nil), "pb.FilmAllMessage")
	proto.RegisterType((*MovieDetailReq)(nil), "pb.MovieDetailReq")
	proto.RegisterType((*MovieDetailRep)(nil), "pb.MovieDetailRep")
	proto.RegisterType((*Release)(nil), "pb.Release")
	proto.RegisterType((*MovieCreditsWithTypesReq)(nil), "pb.MovieCreditsWithTypesReq")
	proto.RegisterType((*MovieCreditsWithTypesRep)(nil), "pb.MovieCreditsWithTypesRep")
	proto.RegisterType((*Type)(nil), "pb.Type")
	proto.RegisterType((*Persons)(nil), "pb.Persons")
	proto.RegisterType((*ImageAllReq)(nil), "pb.ImageAllReq")
	proto.RegisterType((*ImageAllRep)(nil), "pb.ImageAllRep")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*LocationMoviesReq)(nil), "pb.LocationMoviesReq")
	proto.RegisterType((*LocationMoviesRep)(nil), "pb.LocationMoviesRep")
	proto.RegisterType((*MovieComingNewReq)(nil), "pb.MovieComingNewReq")
	proto.RegisterType((*MovieComingNewRep)(nil), "pb.MovieComingNewRep")
	proto.RegisterType((*SearchRep)(nil), "pb.SearchRep")
	proto.RegisterType((*SearchReq)(nil), "pb.SearchReq")
	proto.RegisterType((*SearchMovie)(nil), "pb.SearchMovie")
	proto.RegisterType((*Genres)(nil), "pb.Genres")
	proto.RegisterType((*Rating)(nil), "pb.Rating")
	proto.RegisterType((*Images)(nil), "pb.Images")
	proto.RegisterType((*DayMovie)(nil), "pb.DayMovie")
	proto.RegisterType((*GetFilmsByCidADayReq)(nil), "pb.GetFilmsByCidADayReq")
	proto.RegisterType((*GetFilmsByCidADayRsp)(nil), "pb.GetFilmsByCidADayRsp")
}

func init() { proto.RegisterFile("film.ext.proto", fileDescriptor_7713d3e051ba96f1) }

var fileDescriptor_7713d3e051ba96f1 = []byte{
	// 1600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xdb, 0x6e, 0x1c, 0x37,
	0x12, 0xf5, 0x5c, 0x34, 0x97, 0x1a, 0x5d, 0x69, 0x49, 0xdb, 0x9e, 0x95, 0x05, 0x2d, 0xb1, 0x8b,
	0x15, 0x76, 0x01, 0x61, 0x21, 0xef, 0x6e, 0x90, 0x00, 0x01, 0x2c, 0x6b, 0x64, 0x7b, 0x02, 0x4b,
	0x30, 0x7a, 0x1c, 0x38, 0x79, 0x6c, 0xf5, 0xd0, 0x23, 0x26, 0x7d, 0x53, 0x37, 0x25, 0x79, 0xbe,
	0x20, 0x79, 0xca, 0xbf, 0xe4, 0x25, 0x01, 0xf2, 0x5f, 0x79, 0x0f, 0xaa, 0x48, 0xf6, 0x74, 0x4f,
	0xf7, 0x04, 0x7e, 0x12, 0xeb, 0xb0, 0x58, 0x4d, 0x16, 0x4f, 0x1d, 0xd6, 0x08, 0x36, 0x3f, 0xc8,
	0x20, 0x3c, 0x11, 0x1f, 0xd5, 0x49, 0x92, 0xc6, 0x2a, 0x66, 0xcd, 0xe4, 0x9a, 0x9f, 0xc0, 0xf6,
	0xeb, 0x58, 0xbd, 0x0d, 0xbc, 0xf9, 0x65, 0x7c, 0x2f, 0x45, 0xe6, 0x8a, 0x5b, 0x36, 0x84, 0x5e,
	0x10, 0xfb, 0x9e, 0x92, 0x71, 0xe4, 0x34, 0x8e, 0x1a, 0xc7, 0x2d, 0x37, 0xb7, 0xf9, 0xff, 0x2a,
	0xfe, 0x09, 0xfb, 0x1b, 0x74, 0x42, 0x32, 0x9c, 0xc6, 0x51, 0xeb, 0x78, 0x70, 0xda, 0x3f, 0x49,
	0xae, 0x4f, 0x68, 0xda, 0x35, 0x13, 0xfc, 0xf7, 0x06, 0xac, 0x11, 0xc2, 0xb6, 0xa1, 0x25, 0xc3,
	0x19, 0xc5, 0xed, 0xbb, 0x38, 0x64, 0x0e, 0x74, 0xc9, 0x6b, 0x3c, 0x75, 0x9a, 0xf4, 0x35, 0x6b,
	0xe2, 0x8c, 0x92, 0x2a, 0x10, 0xe7, 0x91, 0xd3, 0x22, 0x7f, 0x6b, 0xb2, 0x7f, 0xc1, 0x36, 0x39,
	0x4d, 0xee, 0x92, 0x24, 0x4e, 0xd5, 0xbb, 0x79, 0x22, 0x9c, 0x36, 0xb9, 0x54, 0x70, 0xc6, 0x61,
	0x1d, 0x0f, 0x3e, 0x92, 0xa9, 0xf0, 0x55, 0x9c, 0x3a, 0x6b, 0xe4, 0x57, 0xc2, 0xd8, 0x3e, 0x74,
	0x3c, 0x1c, 0x64, 0x4e, 0x87, 0x66, 0x8d, 0xc5, 0x0e, 0xa0, 0x4f, 0x7e, 0xa9, 0x17, 0x7a, 0x4e,
	0x97, 0xa6, 0x16, 0x00, 0x3b, 0x82, 0x41, 0xea, 0x29, 0x19, 0xcd, 0x5e, 0xca, 0xc8, 0x0b, 0x9c,
	0xde, 0x51, 0xe3, 0xb8, 0xe9, 0x16, 0x21, 0xfe, 0x5b, 0x1b, 0x7a, 0xaf, 0x63, 0xa5, 0x8f, 0x7e,
	0x00, 0x7d, 0x0a, 0x7b, 0xe5, 0x85, 0x82, 0x52, 0xd5, 0x77, 0x17, 0x00, 0xfb, 0x3b, 0x6c, 0xf8,
	0x71, 0x18, 0xc6, 0xd1, 0x24, 0x11, 0xbe, 0xf4, 0x02, 0x4a, 0x46, 0xdf, 0x2d, 0x83, 0x78, 0x98,
	0xa9, 0xd9, 0x34, 0x85, 0xd1, 0x79, 0x29, 0x61, 0x36, 0xc5, 0xed, 0x45, 0x8a, 0x19, 0xb4, 0x65,
	0xf6, 0x6c, 0x44, 0x47, 0x6f, 0xb9, 0x34, 0xc6, 0x23, 0xcb, 0x6c, 0x74, 0x79, 0xf6, 0x0d, 0x1d,
	0xb9, 0xe5, 0x1a, 0x0b, 0x6f, 0x5f, 0x66, 0x2f, 0x65, 0xa0, 0x44, 0x4a, 0x27, 0x6e, 0xb9, 0xb9,
	0xcd, 0x76, 0x61, 0x4d, 0x66, 0xaf, 0x63, 0x45, 0x47, 0x6d, 0xb9, 0xda, 0xd0, 0x91, 0xc6, 0x18,
	0xa9, 0x6f, 0x23, 0x8d, 0xf3, 0x48, 0x38, 0x7a, 0x36, 0x72, 0xc0, 0x46, 0xd2, 0xb6, 0x8e, 0x74,
	0x25, 0x1e, 0x9c, 0x81, 0x8d, 0x74, 0x25, 0x1e, 0x30, 0x52, 0x20, 0xa2, 0x99, 0xba, 0x71, 0xd6,
	0x75, 0x24, 0x6d, 0x15, 0x29, 0xb2, 0x51, 0xa6, 0x08, 0x83, 0x76, 0x3a, 0xf2, 0xe6, 0xce, 0xa6,
	0x3e, 0x19, 0x8e, 0x31, 0x4a, 0x7a, 0x19, 0x47, 0xea, 0xc6, 0xd9, 0xd2, 0x51, 0xb4, 0x85, 0xdf,
	0x4c, 0xbf, 0x15, 0x5e, 0xea, 0x6c, 0xeb, 0x6f, 0x92, 0xb1, 0x7c, 0x89, 0x3b, 0x95, 0x4b, 0x64,
	0xeb, 0xd0, 0x50, 0x0e, 0xa3, 0x6c, 0x36, 0x54, 0x91, 0x94, 0x8f, 0xcb, 0xa4, 0xb4, 0x33, 0x17,
	0x91, 0xb3, 0x5b, 0x98, 0xb9, 0x88, 0x70, 0x97, 0x0a, 0x29, 0xba, 0x47, 0x30, 0x8d, 0xf1, 0xbb,
	0x0f, 0x5e, 0xa4, 0xc4, 0xf4, 0x3c, 0xbe, 0x8b, 0x94, 0xb3, 0x4f, 0x7b, 0x2a, 0x42, 0xfc, 0x97,
	0x2e, 0x6c, 0xbe, 0x94, 0x41, 0x78, 0x16, 0x04, 0x97, 0x22, 0xcb, 0xbc, 0x99, 0xc0, 0x40, 0x41,
	0x3c, 0x8b, 0x4d, 0xf9, 0xd0, 0x18, 0xd3, 0x8c, 0x94, 0x7c, 0x13, 0x47, 0x33, 0x53, 0x40, 0xb9,
	0x8d, 0x74, 0x91, 0xd9, 0x44, 0x04, 0xc2, 0x57, 0x13, 0xe1, 0x29, 0xa2, 0x4b, 0xcb, 0x2d, 0x61,
	0x96, 0xe3, 0x6f, 0x53, 0xe9, 0xeb, 0x22, 0x6a, 0xba, 0x0b, 0x00, 0x2b, 0x0d, 0x8d, 0x89, 0x9f,
	0x0a, 0x11, 0x3d, 0xa4, 0x12, 0x69, 0xa1, 0x2b, 0xa8, 0x82, 0xb3, 0x43, 0x00, 0x64, 0xab, 0x88,
	0xd4, 0xd5, 0x5d, 0x68, 0x68, 0x55, 0x40, 0xec, 0x4e, 0x89, 0xb8, 0xba, 0x98, 0x72, 0x9b, 0x9d,
	0xc2, 0xae, 0xcc, 0x4c, 0xd9, 0x8e, 0xa3, 0x40, 0x46, 0xe2, 0xbd, 0xa7, 0xfc, 0x1b, 0xc3, 0xb4,
	0xda, 0x39, 0x8c, 0xe7, 0xa7, 0xc2, 0x53, 0xe2, 0x4c, 0x11, 0xf5, 0xfa, 0x6e, 0x6e, 0xe3, 0x65,
	0x5c, 0xcb, 0x19, 0x09, 0x83, 0xe6, 0x9e, 0x35, 0xcb, 0x35, 0x3d, 0x58, 0xae, 0xe9, 0x63, 0xd8,
	0xba, 0xcb, 0x44, 0x7a, 0xe6, 0xfb, 0x22, 0xcb, 0xde, 0xc9, 0x50, 0x64, 0x86, 0x8b, 0xcb, 0x30,
	0x16, 0x2c, 0x2e, 0x7b, 0x11, 0x7f, 0x8c, 0x3f, 0x7c, 0xc0, 0xdc, 0x6d, 0x50, 0xee, 0xca, 0x60,
	0x45, 0x7d, 0x36, 0x6b, 0xd4, 0xe7, 0x04, 0x18, 0x06, 0x7f, 0x23, 0xbf, 0xd7, 0x07, 0xd3, 0x9f,
	0xd5, 0xe4, 0xad, 0x99, 0xc1, 0x3b, 0x41, 0xf4, 0x5c, 0x67, 0x56, 0x7b, 0x6b, 0x4e, 0x57, 0x70,
	0x23, 0x2b, 0x89, 0x17, 0xcd, 0xc7, 0x59, 0x76, 0x27, 0xa6, 0x44, 0x70, 0x2d, 0x2b, 0x0b, 0x10,
	0xb3, 0xe5, 0x23, 0xe7, 0xd2, 0xb9, 0x21, 0xba, 0x35, 0x71, 0xff, 0xe6, 0x06, 0x27, 0x7e, 0x9c,
	0x0a, 0xe2, 0x7c, 0xd3, 0x2d, 0x61, 0xb9, 0xbc, 0xec, 0xd6, 0xca, 0xcb, 0xde, 0x4a, 0x79, 0xd9,
	0x5f, 0x25, 0x2f, 0x7f, 0xa9, 0x97, 0x17, 0x67, 0xa5, 0xbc, 0x3c, 0x59, 0x25, 0x2f, 0xc3, 0xa2,
	0xbc, 0x58, 0xb1, 0xf8, 0x6b, 0xad, 0x58, 0x1c, 0xd4, 0x8b, 0xc5, 0xd3, 0xa2, 0x58, 0x54, 0x44,
	0xfa, 0xb0, 0x46, 0xa4, 0xf9, 0x57, 0xb0, 0x49, 0x8a, 0x3f, 0x12, 0xca, 0x93, 0x01, 0x3e, 0xa9,
	0x87, 0x00, 0xf6, 0x09, 0x1d, 0x4f, 0xcd, 0xa3, 0x5a, 0x40, 0x56, 0xbf, 0x81, 0xfc, 0xd7, 0xe6,
	0x52, 0xb0, 0x84, 0x0e, 0x17, 0x7a, 0x33, 0x61, 0x54, 0x40, 0x1b, 0x45, 0x5d, 0x6a, 0xae, 0xd4,
	0xa5, 0x56, 0x59, 0x97, 0xf0, 0xf0, 0x24, 0x74, 0xa6, 0xee, 0x8d, 0x85, 0x89, 0x9a, 0xe3, 0xd9,
	0xcd, 0x7b, 0x81, 0x63, 0x4d, 0x91, 0x48, 0x89, 0x48, 0x99, 0x37, 0xd2, 0x9a, 0xb9, 0xba, 0x75,
	0x0b, 0xea, 0xe6, 0x40, 0x37, 0xbd, 0x8b, 0x90, 0x82, 0xa6, 0x82, 0xad, 0x59, 0x4d, 0x61, 0xbf,
	0xee, 0x9d, 0x1b, 0x42, 0xcf, 0xbe, 0x69, 0x54, 0xbf, 0x7d, 0x37, 0xb7, 0xd9, 0x3f, 0xa0, 0x9b,
	0x8a, 0x40, 0x78, 0x99, 0xa0, 0xf2, 0x1d, 0x9c, 0x0e, 0xb0, 0xe1, 0x70, 0x35, 0xe4, 0xda, 0x39,
	0xfe, 0x39, 0x74, 0x0d, 0x56, 0xe9, 0x68, 0xfa, 0x8b, 0x8e, 0x06, 0x77, 0x3f, 0xf5, 0x94, 0x30,
	0x49, 0xa3, 0x31, 0xff, 0x2f, 0x38, 0x94, 0xf3, 0xf3, 0x54, 0x4c, 0xa5, 0xca, 0xde, 0x4b, 0x75,
	0x83, 0xd2, 0x41, 0xdd, 0x91, 0x03, 0xdd, 0x4b, 0x73, 0x55, 0xfa, 0x1e, 0xad, 0xc9, 0xbf, 0x58,
	0xb9, 0x2a, 0x61, 0x87, 0xb0, 0x86, 0x79, 0xb1, 0x2d, 0x52, 0x0f, 0x77, 0x8c, 0x93, 0xae, 0x86,
	0xb9, 0x84, 0x36, 0x89, 0xd3, 0x10, 0x7a, 0x08, 0x98, 0x16, 0x81, 0x76, 0x6a, 0x6d, 0x24, 0x91,
	0x1d, 0x5f, 0xf8, 0x66, 0xbf, 0x05, 0x04, 0xf3, 0x92, 0x88, 0x34, 0x8b, 0xa3, 0xcc, 0x69, 0xd1,
	0x57, 0x28, 0x2f, 0x6f, 0x35, 0xe4, 0xda, 0x39, 0xfe, 0x43, 0x03, 0xba, 0x06, 0x5c, 0x41, 0x25,
	0x06, 0xed, 0x08, 0x37, 0x60, 0x52, 0x82, 0x63, 0xa4, 0x0a, 0xfe, 0xcd, 0x39, 0x64, 0x2c, 0x54,
	0xd3, 0x34, 0x0e, 0xc4, 0x79, 0x7c, 0x2f, 0x52, 0xd3, 0x72, 0x2c, 0x00, 0x9c, 0xd5, 0x9f, 0xc5,
	0x0c, 0xeb, 0x67, 0x63, 0x01, 0xf0, 0x7f, 0xc2, 0x60, 0x8c, 0x1f, 0x3c, 0x0b, 0x02, 0x93, 0xd9,
	0x15, 0x45, 0xf0, 0x9f, 0xa2, 0x23, 0x35, 0x9c, 0xb4, 0xd1, 0x52, 0xc3, 0x49, 0x0e, 0xae, 0x99,
	0xe0, 0x4f, 0x61, 0x8d, 0x80, 0xfa, 0x13, 0xf2, 0xc7, 0xb0, 0xf3, 0xc6, 0x10, 0x20, 0xef, 0x7b,
	0xf9, 0xff, 0xab, 0xe0, 0x27, 0x35, 0xb7, 0x8f, 0x61, 0x47, 0xdf, 0x7b, 0x1c, 0xca, 0x68, 0x76,
	0x25, 0x1e, 0x4c, 0xb0, 0x65, 0xf0, 0x93, 0x82, 0x5d, 0x41, 0x7f, 0x22, 0xbc, 0xd4, 0xbf, 0x41,
	0xff, 0x7f, 0x43, 0x2f, 0xbb, 0xbb, 0xfe, 0x4e, 0xf8, 0xca, 0xae, 0xd8, 0xc2, 0x15, 0xda, 0x41,
	0xaf, 0xcb, 0x1d, 0xf0, 0xa4, 0x2a, 0x56, 0xa6, 0x71, 0x6c, 0xb9, 0xda, 0xe0, 0x4f, 0x16, 0xf1,
	0x6e, 0xb1, 0x93, 0xb9, 0x35, 0x89, 0x68, 0xdc, 0xf2, 0x9f, 0x1b, 0x30, 0x28, 0x84, 0xa2, 0x00,
	0x28, 0x0c, 0x36, 0x55, 0x64, 0xb0, 0x4d, 0x68, 0xca, 0xa9, 0xa1, 0x42, 0x53, 0x4e, 0xd9, 0x91,
	0x4d, 0x68, 0x8b, 0x6a, 0x0f, 0xf2, 0xdc, 0x67, 0x96, 0x3e, 0x1c, 0x3a, 0x33, 0x11, 0xa5, 0x22,
	0x73, 0xda, 0xb4, 0x67, 0x72, 0x79, 0x45, 0x88, 0x6b, 0x66, 0x4a, 0x0a, 0xd3, 0x37, 0x0a, 0xc3,
	0x73, 0x35, 0xea, 0x2c, 0x42, 0xbb, 0x84, 0x58, 0x65, 0xe2, 0x07, 0xd0, 0x79, 0x95, 0x47, 0x20,
	0xd5, 0x69, 0x2c, 0x54, 0x87, 0x73, 0xe8, 0x68, 0x7f, 0xe4, 0x92, 0x77, 0x2f, 0x52, 0x7b, 0xf1,
	0x4d, 0xd7, 0x9a, 0xfc, 0x10, 0x3a, 0x7a, 0xbb, 0x78, 0xde, 0x2c, 0xf4, 0x82, 0xc0, 0x9e, 0x97,
	0x0c, 0xfe, 0x53, 0x13, 0x7a, 0x23, 0xf3, 0xf3, 0x86, 0x9a, 0x43, 0xad, 0x21, 0x24, 0x65, 0xda,
	0xb1, 0x08, 0x15, 0x5a, 0xd6, 0x66, 0xa9, 0x65, 0x2d, 0xac, 0xc4, 0x5d, 0xb6, 0xca, 0x2b, 0xb1,
	0xd4, 0xf7, 0xa1, 0x13, 0xde, 0x50, 0xa1, 0xeb, 0xb2, 0x31, 0x16, 0x76, 0x20, 0xc6, 0x6d, 0x24,
	0x33, 0x7a, 0x86, 0x29, 0x4b, 0x4d, 0x77, 0x19, 0x2e, 0x16, 0x4c, 0xa7, 0xd2, 0x16, 0x87, 0x37,
	0xe3, 0xa9, 0x69, 0xe0, 0x69, 0x4c, 0xdd, 0x92, 0x8c, 0x44, 0xe8, 0x8d, 0xa7, 0x46, 0x93, 0x73,
	0xbb, 0xd4, 0x99, 0xf5, 0xcb, 0x9d, 0x19, 0xbf, 0x86, 0xdd, 0x57, 0x42, 0x61, 0x23, 0x9a, 0xbd,
	0x98, 0x9f, 0xcb, 0xe9, 0xd9, 0xc8, 0x9b, 0x9b, 0x9f, 0x89, 0x79, 0xbc, 0xc6, 0x52, 0xbc, 0x7d,
	0xe8, 0xe0, 0xfa, 0xbc, 0x92, 0x8d, 0x85, 0xf8, 0xd4, 0x9b, 0x63, 0x77, 0xa8, 0x3b, 0x51, 0x63,
	0xf1, 0xe7, 0x75, 0xdf, 0xc8, 0x12, 0x76, 0x0c, 0xbd, 0xa9, 0xb9, 0x0b, 0x53, 0x00, 0xeb, 0x48,
	0x0a, 0x7b, 0x3f, 0x6e, 0x3e, 0x7b, 0xfa, 0x63, 0x5b, 0x37, 0xcb, 0x13, 0x91, 0xde, 0x4b, 0x5f,
	0x5c, 0x7c, 0x54, 0xec, 0x4b, 0xd8, 0x28, 0xfd, 0x56, 0x65, 0xbb, 0xb8, 0x76, 0xf9, 0xe7, 0xee,
	0xb0, 0x0e, 0x4d, 0xf8, 0x23, 0xf6, 0x19, 0x0c, 0x0a, 0x0f, 0x2f, 0x63, 0x79, 0xad, 0xe6, 0xcf,
	0xfa, 0xb0, 0x8a, 0xe1, 0xc2, 0xaf, 0x61, 0xaf, 0xf6, 0x1d, 0x60, 0x07, 0xb9, 0x7b, 0xcd, 0xc3,
	0x32, 0xfc, 0xb3, 0x59, 0x0c, 0x7b, 0x02, 0x3d, 0x2b, 0x82, 0x6c, 0x2b, 0xaf, 0x3a, 0xad, 0x9d,
	0xc3, 0x25, 0x00, 0xfd, 0x9f, 0xc3, 0x66, 0x59, 0xce, 0xd8, 0x1e, 0x3a, 0x55, 0x74, 0x6f, 0x58,
	0x0b, 0x9b, 0x08, 0x65, 0x0d, 0xd3, 0x11, 0x2a, 0x62, 0x37, 0xac, 0x85, 0x31, 0xc2, 0x31, 0x74,
	0xb4, 0xc2, 0xb0, 0x8d, 0x85, 0x70, 0xe1, 0x8a, 0x92, 0x89, 0x9e, 0x63, 0xd8, 0xa9, 0x30, 0x80,
	0x39, 0x5a, 0x39, 0xaa, 0xe4, 0x1b, 0xae, 0x98, 0xc9, 0x12, 0xfe, 0xe8, 0xba, 0x43, 0xff, 0xde,
	0x78, 0xf6, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x1d, 0x04, 0x30, 0xf0, 0x10, 0x00, 0x00,
}
