// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServiceExt service

type UserServiceExtService interface {
	// 注册用户
	RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error)
	// 用户登录
	LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error)
	// 密码重置
	ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error)
	// 评分
	WantScore(ctx context.Context, in *WantScoreReq, opts ...client.CallOption) (*WantScoreRsp, error)
	// 修改用户信息
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...client.CallOption) (*UpdateUserProfileRsp, error)
}

type userServiceExtService struct {
	c    client.Client
	name string
}

func NewUserServiceExtService(name string, c client.Client) UserServiceExtService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb"
	}
	return &userServiceExtService{
		c:    c,
		name: name,
	}
}

func (c *userServiceExtService) RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error) {
	req := c.c.NewRequest(c.name, "UserServiceExt.RegistAccount", in)
	out := new(RegistAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtService) LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error) {
	req := c.c.NewRequest(c.name, "UserServiceExt.LoginAccount", in)
	out := new(LoginAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtService) ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error) {
	req := c.c.NewRequest(c.name, "UserServiceExt.ResetAccount", in)
	out := new(ResetAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtService) WantScore(ctx context.Context, in *WantScoreReq, opts ...client.CallOption) (*WantScoreRsp, error) {
	req := c.c.NewRequest(c.name, "UserServiceExt.WantScore", in)
	out := new(WantScoreRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...client.CallOption) (*UpdateUserProfileRsp, error) {
	req := c.c.NewRequest(c.name, "UserServiceExt.UpdateUserProfile", in)
	out := new(UpdateUserProfileRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceExt service

type UserServiceExtHandler interface {
	// 注册用户
	RegistAccount(context.Context, *RegistAccountReq, *RegistAccountRsp) error
	// 用户登录
	LoginAccount(context.Context, *LoginAccountReq, *LoginAccountRsp) error
	// 密码重置
	ResetAccount(context.Context, *ResetAccountReq, *ResetAccountRsp) error
	// 评分
	WantScore(context.Context, *WantScoreReq, *WantScoreRsp) error
	// 修改用户信息
	UpdateUserProfile(context.Context, *UpdateUserProfileReq, *UpdateUserProfileRsp) error
}

func RegisterUserServiceExtHandler(s server.Server, hdlr UserServiceExtHandler, opts ...server.HandlerOption) error {
	type userServiceExt interface {
		RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error
		LoginAccount(ctx context.Context, in *LoginAccountReq, out *LoginAccountRsp) error
		ResetAccount(ctx context.Context, in *ResetAccountReq, out *ResetAccountRsp) error
		WantScore(ctx context.Context, in *WantScoreReq, out *WantScoreRsp) error
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, out *UpdateUserProfileRsp) error
	}
	type UserServiceExt struct {
		userServiceExt
	}
	h := &userServiceExtHandler{hdlr}
	return s.Handle(s.NewHandler(&UserServiceExt{h}, opts...))
}

type userServiceExtHandler struct {
	UserServiceExtHandler
}

func (h *userServiceExtHandler) RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error {
	return h.UserServiceExtHandler.RegistAccount(ctx, in, out)
}

func (h *userServiceExtHandler) LoginAccount(ctx context.Context, in *LoginAccountReq, out *LoginAccountRsp) error {
	return h.UserServiceExtHandler.LoginAccount(ctx, in, out)
}

func (h *userServiceExtHandler) ResetAccount(ctx context.Context, in *ResetAccountReq, out *ResetAccountRsp) error {
	return h.UserServiceExtHandler.ResetAccount(ctx, in, out)
}

func (h *userServiceExtHandler) WantScore(ctx context.Context, in *WantScoreReq, out *WantScoreRsp) error {
	return h.UserServiceExtHandler.WantScore(ctx, in, out)
}

func (h *userServiceExtHandler) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, out *UpdateUserProfileRsp) error {
	return h.UserServiceExtHandler.UpdateUserProfile(ctx, in, out)
}
