// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistAccountReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistAccountReq) Reset()         { *m = RegistAccountReq{} }
func (m *RegistAccountReq) String() string { return proto.CompactTextString(m) }
func (*RegistAccountReq) ProtoMessage()    {}
func (*RegistAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{0}
}

func (m *RegistAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistAccountReq.Unmarshal(m, b)
}
func (m *RegistAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistAccountReq.Marshal(b, m, deterministic)
}
func (m *RegistAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistAccountReq.Merge(m, src)
}
func (m *RegistAccountReq) XXX_Size() int {
	return xxx_messageInfo_RegistAccountReq.Size(m)
}
func (m *RegistAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegistAccountReq proto.InternalMessageInfo

func (m *RegistAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegistAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegistAccountRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistAccountRsp) Reset()         { *m = RegistAccountRsp{} }
func (m *RegistAccountRsp) String() string { return proto.CompactTextString(m) }
func (*RegistAccountRsp) ProtoMessage()    {}
func (*RegistAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{1}
}

func (m *RegistAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistAccountRsp.Unmarshal(m, b)
}
func (m *RegistAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistAccountRsp.Marshal(b, m, deterministic)
}
func (m *RegistAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistAccountRsp.Merge(m, src)
}
func (m *RegistAccountRsp) XXX_Size() int {
	return xxx_messageInfo_RegistAccountRsp.Size(m)
}
func (m *RegistAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegistAccountRsp proto.InternalMessageInfo

type LoginAccountReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountReq) Reset()         { *m = LoginAccountReq{} }
func (m *LoginAccountReq) String() string { return proto.CompactTextString(m) }
func (*LoginAccountReq) ProtoMessage()    {}
func (*LoginAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{2}
}

func (m *LoginAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountReq.Unmarshal(m, b)
}
func (m *LoginAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountReq.Marshal(b, m, deterministic)
}
func (m *LoginAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountReq.Merge(m, src)
}
func (m *LoginAccountReq) XXX_Size() int {
	return xxx_messageInfo_LoginAccountReq.Size(m)
}
func (m *LoginAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountReq proto.InternalMessageInfo

func (m *LoginAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAccountRsp struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAccountRsp) Reset()         { *m = LoginAccountRsp{} }
func (m *LoginAccountRsp) String() string { return proto.CompactTextString(m) }
func (*LoginAccountRsp) ProtoMessage()    {}
func (*LoginAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{3}
}

func (m *LoginAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAccountRsp.Unmarshal(m, b)
}
func (m *LoginAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAccountRsp.Marshal(b, m, deterministic)
}
func (m *LoginAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAccountRsp.Merge(m, src)
}
func (m *LoginAccountRsp) XXX_Size() int {
	return xxx_messageInfo_LoginAccountRsp.Size(m)
}
func (m *LoginAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAccountRsp proto.InternalMessageInfo

func (m *LoginAccountRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoginAccountRsp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginAccountRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAccountRsp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ResetAccountReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetAccountReq) Reset()         { *m = ResetAccountReq{} }
func (m *ResetAccountReq) String() string { return proto.CompactTextString(m) }
func (*ResetAccountReq) ProtoMessage()    {}
func (*ResetAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{4}
}

func (m *ResetAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetAccountReq.Unmarshal(m, b)
}
func (m *ResetAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetAccountReq.Marshal(b, m, deterministic)
}
func (m *ResetAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetAccountReq.Merge(m, src)
}
func (m *ResetAccountReq) XXX_Size() int {
	return xxx_messageInfo_ResetAccountReq.Size(m)
}
func (m *ResetAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetAccountReq proto.InternalMessageInfo

type ResetAccountRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetAccountRsp) Reset()         { *m = ResetAccountRsp{} }
func (m *ResetAccountRsp) String() string { return proto.CompactTextString(m) }
func (*ResetAccountRsp) ProtoMessage()    {}
func (*ResetAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{5}
}

func (m *ResetAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetAccountRsp.Unmarshal(m, b)
}
func (m *ResetAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetAccountRsp.Marshal(b, m, deterministic)
}
func (m *ResetAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetAccountRsp.Merge(m, src)
}
func (m *ResetAccountRsp) XXX_Size() int {
	return xxx_messageInfo_ResetAccountRsp.Size(m)
}
func (m *ResetAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetAccountRsp proto.InternalMessageInfo

type WantScoreReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WantScoreReq) Reset()         { *m = WantScoreReq{} }
func (m *WantScoreReq) String() string { return proto.CompactTextString(m) }
func (*WantScoreReq) ProtoMessage()    {}
func (*WantScoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{6}
}

func (m *WantScoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantScoreReq.Unmarshal(m, b)
}
func (m *WantScoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantScoreReq.Marshal(b, m, deterministic)
}
func (m *WantScoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantScoreReq.Merge(m, src)
}
func (m *WantScoreReq) XXX_Size() int {
	return xxx_messageInfo_WantScoreReq.Size(m)
}
func (m *WantScoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WantScoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_WantScoreReq proto.InternalMessageInfo

func (m *WantScoreReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WantScoreReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *WantScoreReq) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type WantScoreRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WantScoreRsp) Reset()         { *m = WantScoreRsp{} }
func (m *WantScoreRsp) String() string { return proto.CompactTextString(m) }
func (*WantScoreRsp) ProtoMessage()    {}
func (*WantScoreRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{7}
}

func (m *WantScoreRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantScoreRsp.Unmarshal(m, b)
}
func (m *WantScoreRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantScoreRsp.Marshal(b, m, deterministic)
}
func (m *WantScoreRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantScoreRsp.Merge(m, src)
}
func (m *WantScoreRsp) XXX_Size() int {
	return xxx_messageInfo_WantScoreRsp.Size(m)
}
func (m *WantScoreRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WantScoreRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WantScoreRsp proto.InternalMessageInfo

type UpdateUserProfileReq struct {
	UserImage            string   `protobuf:"bytes,1,opt,name=userImage,proto3" json:"userImage,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string   `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	UserPhone            string   `protobuf:"bytes,4,opt,name=userPhone,proto3" json:"userPhone,omitempty"`
	UserID               int64    `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileReq) Reset()         { *m = UpdateUserProfileReq{} }
func (m *UpdateUserProfileReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileReq) ProtoMessage()    {}
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{8}
}

func (m *UpdateUserProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileReq.Unmarshal(m, b)
}
func (m *UpdateUserProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileReq.Merge(m, src)
}
func (m *UpdateUserProfileReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileReq.Size(m)
}
func (m *UpdateUserProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileReq proto.InternalMessageInfo

func (m *UpdateUserProfileReq) GetUserImage() string {
	if m != nil {
		return m.UserImage
	}
	return ""
}

func (m *UpdateUserProfileReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdateUserProfileReq) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *UpdateUserProfileReq) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *UpdateUserProfileReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type UpdateUserProfileRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileRsp) Reset()         { *m = UpdateUserProfileRsp{} }
func (m *UpdateUserProfileRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRsp) ProtoMessage()    {}
func (*UpdateUserProfileRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85764c91792e488, []int{9}
}

func (m *UpdateUserProfileRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRsp.Unmarshal(m, b)
}
func (m *UpdateUserProfileRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRsp.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRsp.Merge(m, src)
}
func (m *UpdateUserProfileRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRsp.Size(m)
}
func (m *UpdateUserProfileRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegistAccountReq)(nil), "pb.RegistAccountReq")
	proto.RegisterType((*RegistAccountRsp)(nil), "pb.RegistAccountRsp")
	proto.RegisterType((*LoginAccountReq)(nil), "pb.LoginAccountReq")
	proto.RegisterType((*LoginAccountRsp)(nil), "pb.LoginAccountRsp")
	proto.RegisterType((*ResetAccountReq)(nil), "pb.ResetAccountReq")
	proto.RegisterType((*ResetAccountRsp)(nil), "pb.ResetAccountRsp")
	proto.RegisterType((*WantScoreReq)(nil), "pb.WantScoreReq")
	proto.RegisterType((*WantScoreRsp)(nil), "pb.WantScoreRsp")
	proto.RegisterType((*UpdateUserProfileReq)(nil), "pb.UpdateUserProfileReq")
	proto.RegisterType((*UpdateUserProfileRsp)(nil), "pb.UpdateUserProfileRsp")
}

func init() { proto.RegisterFile("user.ext.proto", fileDescriptor_f85764c91792e488) }

var fileDescriptor_f85764c91792e488 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0x5d, 0x92, 0x85, 0x5d, 0x46, 0x2c, 0x1f, 0xde, 0x08, 0x45, 0xd1, 0x1e, 0x56, 0x3e, 0xf5,
	0x14, 0xa9, 0xed, 0xad, 0x52, 0x0f, 0x55, 0xcb, 0x01, 0xa9, 0xaa, 0x50, 0x10, 0xed, 0xb5, 0x21,
	0x99, 0xd2, 0x48, 0x24, 0x36, 0x71, 0xa0, 0xfc, 0xa0, 0xfe, 0x95, 0xfe, 0xaf, 0xca, 0x0e, 0x09,
	0x26, 0xa1, 0xa8, 0xc7, 0xf7, 0xc6, 0x6f, 0xde, 0xe4, 0xcd, 0x04, 0xba, 0x6b, 0x81, 0xa9, 0x8b,
	0xdb, 0xcc, 0xe5, 0x29, 0xcb, 0x18, 0x31, 0xf8, 0x9c, 0x3e, 0x43, 0xdf, 0xc3, 0x45, 0x24, 0xb2,
	0x9b, 0x20, 0x60, 0xeb, 0x24, 0xf3, 0x70, 0x45, 0x2c, 0x68, 0x62, 0xec, 0x47, 0x4b, 0xbb, 0xf1,
	0xbf, 0x71, 0xd6, 0xf6, 0x72, 0x40, 0x1c, 0xf8, 0x2d, 0xf5, 0x0f, 0x7e, 0x8c, 0xb6, 0xa1, 0x0a,
	0x25, 0x96, 0x35, 0xee, 0x0b, 0xf1, 0xc6, 0xd2, 0xd0, 0x36, 0xf3, 0x5a, 0x81, 0x29, 0xa9, 0x3a,
	0x08, 0x4e, 0x6f, 0xa1, 0x77, 0xcf, 0x16, 0x51, 0xf2, 0x1d, 0xd3, 0xb2, 0xb1, 0x51, 0x69, 0xbc,
	0xaa, 0x34, 0x11, 0x9c, 0x0c, 0xa1, 0x25, 0x67, 0x1a, 0xdf, 0xa9, 0x2e, 0xa6, 0xb7, 0x43, 0x27,
	0x67, 0x2f, 0x8d, 0x4d, 0xdd, 0xd8, 0x82, 0x26, 0x7f, 0x65, 0x09, 0xda, 0x3f, 0x73, 0x56, 0x01,
	0x3a, 0x80, 0x9e, 0x87, 0x02, 0xb5, 0xb0, 0x6a, 0x94, 0xe0, 0xf4, 0x11, 0x3a, 0x4f, 0x7e, 0x92,
	0x4d, 0x03, 0x96, 0xa2, 0xfc, 0xb4, 0x62, 0xaa, 0xf0, 0x60, 0xaa, 0x90, 0xd8, 0xf0, 0x2b, 0x66,
	0x9b, 0x08, 0xc7, 0xf9, 0xb7, 0x99, 0x5e, 0x01, 0xa5, 0xbb, 0x90, 0x6a, 0x35, 0x93, 0xe9, 0xe5,
	0x80, 0x76, 0xf5, 0xbe, 0x82, 0xd3, 0xf7, 0x06, 0x58, 0x33, 0x1e, 0xfa, 0x19, 0xce, 0x04, 0xa6,
	0x93, 0x94, 0xbd, 0x44, 0x4b, 0x65, 0xf8, 0x0f, 0xda, 0xca, 0x22, 0xf6, 0x17, 0xb8, 0xcb, 0x73,
	0x4f, 0x9c, 0x0c, 0x63, 0xa7, 0x1c, 0x69, 0x81, 0xec, 0x89, 0xa2, 0x3a, 0xd1, 0x82, 0xd9, 0x13,
	0x5a, 0xf8, 0x4d, 0x3d, 0x7c, 0x3a, 0x3c, 0x36, 0xa5, 0xe0, 0x17, 0x1f, 0x06, 0x74, 0x25, 0x35,
	0xc5, 0x74, 0x13, 0x05, 0x38, 0xda, 0x66, 0xe4, 0x1a, 0xfe, 0x1c, 0xdc, 0x0a, 0xb1, 0x5c, 0x3e,
	0x77, 0xab, 0x07, 0xea, 0x1c, 0x61, 0x05, 0xa7, 0x3f, 0xc8, 0x15, 0x74, 0xf4, 0x8b, 0x20, 0x7f,
	0xe5, 0xbb, 0xca, 0xa1, 0x39, 0x75, 0xb2, 0xd0, 0xea, 0x7b, 0xcc, 0xb5, 0x95, 0x65, 0x3b, 0x75,
	0x52, 0x69, 0xcf, 0xa1, 0x5d, 0x2e, 0x86, 0xf4, 0xe5, 0x1b, 0x7d, 0xff, 0x4e, 0x85, 0x51, 0x92,
	0x31, 0x0c, 0x6a, 0xa1, 0x10, 0x5b, 0x3e, 0x3c, 0xb6, 0x51, 0xe7, 0x8b, 0x8a, 0x6c, 0x35, 0x6f,
	0xa9, 0xbf, 0xf9, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x67, 0x41, 0xe0, 0x37, 0xdf, 0x03, 0x00,
	0x00,
}
